import SwiftUI
import os

/// One package's licence, as generated by `scripts/generate-licenses.sh`.
struct OpenSourceLicense: Codable, Identifiable, Hashable {
    let name: String
    let kind: String
    let copyright: String?
    let text: String
    /// Apache-2.0 requires any NOTICE to travel with the licence.
    let notice: String?

    var id: String { name }
}

/// The open-source licences the app ships.
///
/// MIT and Apache-2.0 both require the licence text to be included with the
/// software, so this cannot be a link to a page — the text has to be in the
/// binary. The list is generated from the resolved packages at build time, which
/// is the only way a new dependency does not quietly go unlisted.
struct OpenSourceLicensesView: View {

    @State private var licenses: [OpenSourceLicense] = []

    private static let logger = Logger(
        subsystem: "com.protoductai.wizmark",
        category: "Licenses"
    )

    var body: some View {
        List {
            Section {
                ForEach(licenses) { license in
                    NavigationLink {
                        detail(license)
                    } label: {
                        VStack(alignment: .leading, spacing: 2) {
                            Text(license.name)
                            Text(license.kind)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                }
            } footer: {
                Text(String(
                    localized: "settings.licenses.footer",
                    defaultValue: "WizMark は以下のオープンソースソフトウェアを利用しています。"
                ))
            }
        }
        .navigationTitle(String(
            localized: "settings.licenses.title",
            defaultValue: "オープンソースライセンス"
        ))
        .navigationBarTitleDisplayMode(.inline)
        .task { load() }
    }

    private func detail(_ license: OpenSourceLicense) -> some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                if let copyright = license.copyright {
                    Text(copyright)
                        .font(.footnote.weight(.medium))
                }

                if let notice = license.notice {
                    Text(notice)
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                    Divider()
                }

                Text(license.text)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding()
            .textSelection(.enabled)
        }
        .navigationTitle(license.name)
        .navigationBarTitleDisplayMode(.inline)
    }

    private func load() {
        guard licenses.isEmpty else { return }
        guard let url = Bundle.main.url(forResource: "OpenSourceLicenses", withExtension: "json"),
              let data = try? Data(contentsOf: url)
        else {
            // Shipping without the file is a build mistake, not something the
            // user can act on, so the screen simply stays empty.
            Self.logger.error("OpenSourceLicenses.json is missing from the bundle")
            return
        }
        licenses = (try? JSONDecoder().decode([OpenSourceLicense].self, from: data)) ?? []
    }
}
