import SwiftUI

struct SFSymbolPicker: View {

    @Binding var selection: String?
    @Environment(\.dismiss) private var dismiss
    @State private var searchText = ""

    private var filtered: [IconCategory] {
        if searchText.isEmpty { return IconCategory.curated }
        let q = searchText.lowercased()
        return IconCategory.curated.compactMap { cat in
            let hits = cat.icons.filter { $0.name.lowercased().contains(q) || $0.label.lowercased().contains(q) }
            return hits.isEmpty ? nil : IconCategory(title: cat.title, icons: hits)
        }
    }

    var body: some View {
        NavigationStack {
            List {
                if selection != nil {
                    Button(String(localized: "collection.form.iconClear", defaultValue: "アイコンを削除"), role: .destructive) {
                        selection = nil
                        dismiss()
                    }
                }
                ForEach(filtered) { cat in
                    Section(cat.title) {
                        LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 6), spacing: 12) {
                            ForEach(cat.icons) { icon in
                                Button {
                                    selection = icon.name
                                    dismiss()
                                } label: {
                                    Image(systemName: icon.name)
                                        .font(.title3)
                                        .frame(width: 44, height: 44)
                                        .background(selection == icon.name ? Color.accentColor.opacity(0.15) : Color(.tertiarySystemFill))
                                        .foregroundStyle(selection == icon.name ? Color.accentColor : .primary)
                                        .clipShape(.rect(cornerRadius: 8))
                                }
                                .buttonStyle(.plain)
                                .accessibilityLabel(icon.label)
                            }
                        }
                        .padding(.vertical, 4)
                    }
                }
            }
            .searchable(text: $searchText, prompt: String(localized: "symbolPicker.searchPrompt", defaultValue: "アイコンを検索"))
            .navigationTitle(String(localized: "symbolPicker.title", defaultValue: "アイコン"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(String(localized: "common.close", defaultValue: "閉じる")) { dismiss() }
                }
            }
        }
    }
}

// MARK: - Data Models

private struct IconItem: Identifiable {
    let name: String
    let label: String
    var id: String { name }
}

private struct IconCategory: Identifiable {
    let title: String
    let icons: [IconItem]
    var id: String { title }

    // swiftlint:disable function_body_length
    static let curated: [IconCategory] = [

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 1. 基本・整理 (Basic & Organization)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.basicOrganization", defaultValue: "基本・整理"), icons: [
            IconItem(name: "folder", label: String(localized: "symbolPicker.icon.folder", defaultValue: "フォルダ")),
            IconItem(name: "folder.fill", label: String(localized: "symbolPicker.icon.folder.fill", defaultValue: "フォルダ(塗り)")),
            IconItem(name: "folder.badge.plus", label: String(localized: "symbolPicker.icon.folder.badge.plus", defaultValue: "フォルダ追加")),
            IconItem(name: "folder.badge.minus", label: String(localized: "symbolPicker.icon.folder.badge.minus", defaultValue: "フォルダ削除")),
            IconItem(name: "folder.badge.gearshape", label: String(localized: "symbolPicker.icon.folder.badge.gearshape", defaultValue: "フォルダ設定")),
            IconItem(name: "folder.badge.person.crop", label: String(localized: "symbolPicker.icon.folder.badge.person.crop", defaultValue: "共有フォルダ")),
            IconItem(name: "star", label: String(localized: "symbolPicker.icon.star", defaultValue: "星")),
            IconItem(name: "star.fill", label: String(localized: "symbolPicker.icon.star.fill", defaultValue: "星(塗り)")),
            IconItem(name: "star.slash", label: String(localized: "symbolPicker.icon.star.slash", defaultValue: "星オフ")),
            IconItem(name: "heart", label: String(localized: "symbolPicker.icon.heart", defaultValue: "ハート")),
            IconItem(name: "heart.fill", label: String(localized: "symbolPicker.icon.heart.fill", defaultValue: "ハート(塗り)")),
            IconItem(name: "heart.slash", label: String(localized: "symbolPicker.icon.heart.slash", defaultValue: "ハートオフ")),
            IconItem(name: "bookmark", label: String(localized: "symbolPicker.icon.bookmark", defaultValue: "ブックマーク")),
            IconItem(name: "bookmark.fill", label: String(localized: "symbolPicker.icon.bookmark.fill", defaultValue: "ブックマーク(塗り)")),
            IconItem(name: "bookmark.slash", label: String(localized: "symbolPicker.icon.bookmark.slash", defaultValue: "ブックマークオフ")),
            IconItem(name: "tag", label: String(localized: "symbolPicker.icon.tag", defaultValue: "タグ")),
            IconItem(name: "tag.fill", label: String(localized: "symbolPicker.icon.tag.fill", defaultValue: "タグ(塗り)")),
            IconItem(name: "tag.slash", label: String(localized: "symbolPicker.icon.tag.slash", defaultValue: "タグオフ")),
            IconItem(name: "flag", label: String(localized: "symbolPicker.icon.flag", defaultValue: "フラグ")),
            IconItem(name: "flag.fill", label: String(localized: "symbolPicker.icon.flag.fill", defaultValue: "フラグ(塗り)")),
            IconItem(name: "flag.slash", label: String(localized: "symbolPicker.icon.flag.slash", defaultValue: "フラグオフ")),
            IconItem(name: "pin", label: String(localized: "symbolPicker.icon.pin", defaultValue: "ピン")),
            IconItem(name: "pin.fill", label: String(localized: "symbolPicker.icon.pin.fill", defaultValue: "ピン(塗り)")),
            IconItem(name: "pin.slash", label: String(localized: "symbolPicker.icon.pin.slash", defaultValue: "ピンオフ")),
            IconItem(name: "bell", label: String(localized: "symbolPicker.icon.bell", defaultValue: "ベル")),
            IconItem(name: "bell.fill", label: String(localized: "symbolPicker.icon.bell.fill", defaultValue: "ベル(塗り)")),
            IconItem(name: "bell.slash", label: String(localized: "symbolPicker.icon.bell.slash", defaultValue: "ベルオフ")),
            IconItem(name: "clock", label: String(localized: "symbolPicker.icon.clock", defaultValue: "時計")),
            IconItem(name: "clock.fill", label: String(localized: "symbolPicker.icon.clock.fill", defaultValue: "時計(塗り)")),
            IconItem(name: "calendar", label: String(localized: "symbolPicker.icon.calendar", defaultValue: "カレンダー")),
            IconItem(name: "checkmark", label: String(localized: "symbolPicker.icon.checkmark", defaultValue: "チェックマーク")),
            IconItem(name: "checkmark.circle", label: String(localized: "symbolPicker.icon.checkmark.circle", defaultValue: "チェック丸")),
            IconItem(name: "checkmark.circle.fill", label: String(localized: "symbolPicker.icon.checkmark.circle.fill", defaultValue: "チェック丸(塗り)")),
            IconItem(name: "archivebox", label: String(localized: "symbolPicker.icon.archivebox", defaultValue: "アーカイブ")),
            IconItem(name: "archivebox.fill", label: String(localized: "symbolPicker.icon.archivebox.fill", defaultValue: "アーカイブ(塗り)")),
            IconItem(name: "tray", label: String(localized: "symbolPicker.icon.tray", defaultValue: "トレイ")),
            IconItem(name: "tray.fill", label: String(localized: "symbolPicker.icon.tray.fill", defaultValue: "トレイ(塗り)")),
            IconItem(name: "tray.and.arrow.down", label: String(localized: "symbolPicker.icon.tray.and.arrow.down", defaultValue: "受信トレイ")),
            IconItem(name: "tray.and.arrow.up", label: String(localized: "symbolPicker.icon.tray.and.arrow.up", defaultValue: "送信トレイ")),
            IconItem(name: "tray.2", label: String(localized: "symbolPicker.icon.tray.2", defaultValue: "トレイ重ね")),
            IconItem(name: "square.grid.2x2", label: String(localized: "symbolPicker.icon.square.grid.2x2", defaultValue: "グリッド2x2")),
            IconItem(name: "list.bullet", label: String(localized: "symbolPicker.icon.list.bullet", defaultValue: "リスト")),
            IconItem(name: "list.dash", label: String(localized: "symbolPicker.icon.list.dash", defaultValue: "リスト(ダッシュ)")),
            IconItem(name: "list.number", label: String(localized: "symbolPicker.icon.list.number", defaultValue: "番号リスト")),
            IconItem(name: "list.star", label: String(localized: "symbolPicker.icon.list.star", defaultValue: "星リスト")),
            IconItem(name: "line.3.horizontal.decrease", label: String(localized: "symbolPicker.icon.line.3.horizontal.decrease", defaultValue: "フィルタ")),
            IconItem(name: "arrow.up.arrow.down", label: String(localized: "symbolPicker.icon.arrow.up.arrow.down", defaultValue: "ソート")),
            IconItem(name: "magnifyingglass", label: String(localized: "symbolPicker.icon.magnifyingglass", defaultValue: "検索")),
            IconItem(name: "eye", label: String(localized: "symbolPicker.icon.eye", defaultValue: "表示")),
            IconItem(name: "eye.slash", label: String(localized: "symbolPicker.icon.eye.slash", defaultValue: "非表示")),
            IconItem(name: "lock", label: String(localized: "symbolPicker.icon.lock", defaultValue: "ロック")),
            IconItem(name: "lock.fill", label: String(localized: "symbolPicker.icon.lock.fill", defaultValue: "ロック(塗り)")),
            IconItem(name: "lock.open", label: String(localized: "symbolPicker.icon.lock.open", defaultValue: "ロック解除")),
            IconItem(name: "shield", label: String(localized: "symbolPicker.icon.shield", defaultValue: "シールド")),
            IconItem(name: "shield.fill", label: String(localized: "symbolPicker.icon.shield.fill", defaultValue: "シールド(塗り)")),
            IconItem(name: "key", label: String(localized: "symbolPicker.icon.key", defaultValue: "鍵")),
            IconItem(name: "key.fill", label: String(localized: "symbolPicker.icon.key.fill", defaultValue: "鍵(塗り)")),
            IconItem(name: "link", label: String(localized: "symbolPicker.icon.link", defaultValue: "リンク")),
            IconItem(name: "paperclip", label: String(localized: "symbolPicker.icon.paperclip", defaultValue: "クリップ")),
            IconItem(name: "ellipsis", label: String(localized: "symbolPicker.icon.ellipsis", defaultValue: "その他")),
            IconItem(name: "ellipsis.circle", label: String(localized: "symbolPicker.icon.ellipsis.circle", defaultValue: "その他(丸)")),
            IconItem(name: "gearshape", label: String(localized: "symbolPicker.icon.gearshape", defaultValue: "設定")),
            IconItem(name: "gearshape.fill", label: String(localized: "symbolPicker.icon.gearshape.fill", defaultValue: "設定(塗り)")),
            IconItem(name: "slider.horizontal.3", label: String(localized: "symbolPicker.icon.slider.horizontal.3", defaultValue: "スライダー")),
            IconItem(name: "line.3.horizontal", label: String(localized: "symbolPicker.icon.line.3.horizontal", defaultValue: "メニュー")),
            IconItem(name: "rectangle.stack", label: String(localized: "symbolPicker.icon.rectangle.stack", defaultValue: "スタック")),
            IconItem(name: "rectangle.stack.fill", label: String(localized: "symbolPicker.icon.rectangle.stack.fill", defaultValue: "スタック(塗り)")),
            IconItem(name: "square.and.arrow.up", label: String(localized: "symbolPicker.icon.square.and.arrow.up", defaultValue: "共有")),
            IconItem(name: "square.and.arrow.down", label: String(localized: "symbolPicker.icon.square.and.arrow.down", defaultValue: "ダウンロード")),
            IconItem(name: "hand.thumbsup", label: String(localized: "symbolPicker.icon.hand.thumbsup", defaultValue: "いいね")),
            IconItem(name: "hand.thumbsup.fill", label: String(localized: "symbolPicker.icon.hand.thumbsup.fill", defaultValue: "いいね(塗り)")),
            IconItem(name: "hand.thumbsdown", label: String(localized: "symbolPicker.icon.hand.thumbsdown", defaultValue: "よくないね")),
            IconItem(name: "trash", label: String(localized: "symbolPicker.icon.trash", defaultValue: "ゴミ箱")),
            IconItem(name: "note.text", label: String(localized: "symbolPicker.icon.note.text", defaultValue: "メモ")),
            IconItem(name: "square.and.pencil", label: String(localized: "symbolPicker.icon.square.and.pencil", defaultValue: "編集")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 2. 仕事・ビジネス (Work & Business)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.workBusiness", defaultValue: "仕事・ビジネス"), icons: [
            IconItem(name: "briefcase", label: String(localized: "symbolPicker.icon.briefcase", defaultValue: "ブリーフケース")),
            IconItem(name: "briefcase.fill", label: String(localized: "symbolPicker.icon.briefcase.fill", defaultValue: "ブリーフケース(塗り)")),
            IconItem(name: "building", label: String(localized: "symbolPicker.icon.building", defaultValue: "ビル")),
            IconItem(name: "building.fill", label: String(localized: "symbolPicker.icon.building.fill", defaultValue: "ビル(塗り)")),
            IconItem(name: "building.2", label: String(localized: "symbolPicker.icon.building.2", defaultValue: "ビル群")),
            IconItem(name: "building.2.fill", label: String(localized: "symbolPicker.icon.building.2.fill", defaultValue: "ビル群(塗り)")),
            IconItem(name: "building.columns", label: String(localized: "symbolPicker.icon.building.columns", defaultValue: "公共施設")),
            IconItem(name: "building.columns.fill", label: String(localized: "symbolPicker.icon.building.columns.fill", defaultValue: "公共施設(塗り)")),
            IconItem(name: "chart.bar", label: String(localized: "symbolPicker.icon.chart.bar", defaultValue: "棒グラフ")),
            IconItem(name: "chart.bar.fill", label: String(localized: "symbolPicker.icon.chart.bar.fill", defaultValue: "棒グラフ(塗り)")),
            IconItem(name: "chart.bar.xaxis", label: String(localized: "symbolPicker.icon.chart.bar.xaxis", defaultValue: "棒グラフ(軸付き)")),
            IconItem(name: "chart.pie", label: String(localized: "symbolPicker.icon.chart.pie", defaultValue: "円グラフ")),
            IconItem(name: "chart.pie.fill", label: String(localized: "symbolPicker.icon.chart.pie.fill", defaultValue: "円グラフ(塗り)")),
            IconItem(name: "chart.line.uptrend.xyaxis", label: String(localized: "symbolPicker.icon.chart.line.uptrend.xyaxis", defaultValue: "折れ線グラフ(上昇)")),
            IconItem(name: "chart.line.downtrend.xyaxis", label: String(localized: "symbolPicker.icon.chart.line.downtrend.xyaxis", defaultValue: "折れ線グラフ(下降)")),
            IconItem(name: "chart.line.flattrend.xyaxis", label: String(localized: "symbolPicker.icon.chart.line.flattrend.xyaxis", defaultValue: "折れ線グラフ(横ばい)")),
            IconItem(name: "chart.xyaxis.line", label: String(localized: "symbolPicker.icon.chart.xyaxis.line", defaultValue: "XYグラフ")),
            IconItem(name: "chart.dots.scatter", label: String(localized: "symbolPicker.icon.chart.dots.scatter", defaultValue: "散布図")),
            IconItem(name: "dollarsign", label: String(localized: "symbolPicker.icon.dollarsign", defaultValue: "ドル")),
            IconItem(name: "dollarsign.circle", label: String(localized: "symbolPicker.icon.dollarsign.circle", defaultValue: "ドル(丸)")),
            IconItem(name: "dollarsign.circle.fill", label: String(localized: "symbolPicker.icon.dollarsign.circle.fill", defaultValue: "ドル(丸塗り)")),
            IconItem(name: "yensign", label: String(localized: "symbolPicker.icon.yensign", defaultValue: "円")),
            IconItem(name: "yensign.circle", label: String(localized: "symbolPicker.icon.yensign.circle", defaultValue: "円(丸)")),
            IconItem(name: "eurosign", label: String(localized: "symbolPicker.icon.eurosign", defaultValue: "ユーロ")),
            IconItem(name: "eurosign.circle", label: String(localized: "symbolPicker.icon.eurosign.circle", defaultValue: "ユーロ(丸)")),
            IconItem(name: "banknote", label: String(localized: "symbolPicker.icon.banknote", defaultValue: "紙幣")),
            IconItem(name: "banknote.fill", label: String(localized: "symbolPicker.icon.banknote.fill", defaultValue: "紙幣(塗り)")),
            IconItem(name: "creditcard", label: String(localized: "symbolPicker.icon.creditcard", defaultValue: "クレジットカード")),
            IconItem(name: "creditcard.fill", label: String(localized: "symbolPicker.icon.creditcard.fill", defaultValue: "クレジットカード(塗り)")),
            IconItem(name: "wallet.pass", label: String(localized: "symbolPicker.icon.wallet.pass", defaultValue: "ウォレット")),
            IconItem(name: "wallet.pass.fill", label: String(localized: "symbolPicker.icon.wallet.pass.fill", defaultValue: "ウォレット(塗り)")),
            IconItem(name: "storefront", label: String(localized: "symbolPicker.icon.storefront", defaultValue: "店舗")),
            IconItem(name: "storefront.fill", label: String(localized: "symbolPicker.icon.storefront.fill", defaultValue: "店舗(塗り)")),
            IconItem(name: "shippingbox", label: String(localized: "symbolPicker.icon.shippingbox", defaultValue: "配送箱")),
            IconItem(name: "shippingbox.fill", label: String(localized: "symbolPicker.icon.shippingbox.fill", defaultValue: "配送箱(塗り)")),
            IconItem(name: "printer", label: String(localized: "symbolPicker.icon.printer", defaultValue: "プリンター")),
            IconItem(name: "printer.fill", label: String(localized: "symbolPicker.icon.printer.fill", defaultValue: "プリンター(塗り)")),
            IconItem(name: "doc", label: String(localized: "symbolPicker.icon.doc", defaultValue: "書類")),
            IconItem(name: "doc.fill", label: String(localized: "symbolPicker.icon.doc.fill", defaultValue: "書類(塗り)")),
            IconItem(name: "doc.text", label: String(localized: "symbolPicker.icon.doc.text", defaultValue: "テキスト書類")),
            IconItem(name: "doc.text.fill", label: String(localized: "symbolPicker.icon.doc.text.fill", defaultValue: "テキスト書類(塗り)")),
            IconItem(name: "doc.on.doc", label: String(localized: "symbolPicker.icon.doc.on.doc", defaultValue: "書類コピー")),
            IconItem(name: "doc.on.clipboard", label: String(localized: "symbolPicker.icon.doc.on.clipboard", defaultValue: "クリップボード")),
            IconItem(name: "clipboard", label: String(localized: "symbolPicker.icon.clipboard", defaultValue: "バインダー")),
            IconItem(name: "clipboard.fill", label: String(localized: "symbolPicker.icon.clipboard.fill", defaultValue: "バインダー(塗り)")),
            IconItem(name: "list.bullet.clipboard", label: String(localized: "symbolPicker.icon.list.bullet.clipboard", defaultValue: "チェックリスト")),
            IconItem(name: "signature", label: String(localized: "symbolPicker.icon.signature", defaultValue: "署名")),
            IconItem(name: "person", label: String(localized: "symbolPicker.icon.person", defaultValue: "人")),
            IconItem(name: "person.fill", label: String(localized: "symbolPicker.icon.person.fill", defaultValue: "人(塗り)")),
            IconItem(name: "person.2", label: String(localized: "symbolPicker.icon.person.2", defaultValue: "二人")),
            IconItem(name: "person.2.fill", label: String(localized: "symbolPicker.icon.person.2.fill", defaultValue: "二人(塗り)")),
            IconItem(name: "person.3", label: String(localized: "symbolPicker.icon.person.3", defaultValue: "三人")),
            IconItem(name: "person.3.fill", label: String(localized: "symbolPicker.icon.person.3.fill", defaultValue: "三人(塗り)")),
            IconItem(name: "person.crop.circle", label: String(localized: "symbolPicker.icon.person.crop.circle", defaultValue: "アイコン")),
            IconItem(name: "calendar.badge.plus", label: String(localized: "symbolPicker.icon.calendar.badge.plus", defaultValue: "予定追加")),
            IconItem(name: "calendar.badge.clock", label: String(localized: "symbolPicker.icon.calendar.badge.clock", defaultValue: "予定時間")),
            IconItem(name: "target", label: String(localized: "symbolPicker.icon.target", defaultValue: "ターゲット")),
            IconItem(name: "percent", label: String(localized: "symbolPicker.icon.percent", defaultValue: "パーセント")),
            IconItem(name: "arrow.triangle.2.circlepath", label: String(localized: "symbolPicker.icon.arrow.triangle.2.circlepath", defaultValue: "繰り返し")),
            IconItem(name: "hourglass", label: String(localized: "symbolPicker.icon.hourglass", defaultValue: "砂時計")),
            IconItem(name: "megaphone", label: String(localized: "symbolPicker.icon.megaphone", defaultValue: "拡声器")),
            IconItem(name: "megaphone.fill", label: String(localized: "symbolPicker.icon.megaphone.fill", defaultValue: "拡声器(塗り)")),
            IconItem(name: "newspaper", label: String(localized: "symbolPicker.icon.newspaper", defaultValue: "新聞")),
            IconItem(name: "newspaper.fill", label: String(localized: "symbolPicker.icon.newspaper.fill", defaultValue: "新聞(塗り)")),
            IconItem(name: "lanyardcard", label: String(localized: "symbolPicker.icon.lanyardcard", defaultValue: "社員証")),
            IconItem(name: "lanyardcard.fill", label: String(localized: "symbolPicker.icon.lanyardcard.fill", defaultValue: "社員証(塗り)")),
            IconItem(name: "network", label: String(localized: "symbolPicker.icon.network", defaultValue: "ネットワーク")),
            IconItem(name: "envelope", label: String(localized: "symbolPicker.icon.envelope", defaultValue: "メール")),
            IconItem(name: "envelope.fill", label: String(localized: "symbolPicker.icon.envelope.fill", defaultValue: "メール(塗り)")),
            IconItem(name: "phone", label: String(localized: "symbolPicker.icon.phone", defaultValue: "電話")),
            IconItem(name: "phone.fill", label: String(localized: "symbolPicker.icon.phone.fill", defaultValue: "電話(塗り)")),
            IconItem(name: "paperplane", label: String(localized: "symbolPicker.icon.paperplane", defaultValue: "紙飛行機")),
            IconItem(name: "paperplane.fill", label: String(localized: "symbolPicker.icon.paperplane.fill", defaultValue: "紙飛行機(塗り)")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 3. 学習・教育 (Learning & Education)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.learningEducation", defaultValue: "学習・教育"), icons: [
            IconItem(name: "book", label: String(localized: "symbolPicker.icon.book", defaultValue: "本")),
            IconItem(name: "book.fill", label: String(localized: "symbolPicker.icon.book.fill", defaultValue: "本(塗り)")),
            IconItem(name: "book.closed", label: String(localized: "symbolPicker.icon.book.closed", defaultValue: "閉じた本")),
            IconItem(name: "book.closed.fill", label: String(localized: "symbolPicker.icon.book.closed.fill", defaultValue: "閉じた本(塗り)")),
            IconItem(name: "books.vertical", label: String(localized: "symbolPicker.icon.books.vertical", defaultValue: "本棚")),
            IconItem(name: "books.vertical.fill", label: String(localized: "symbolPicker.icon.books.vertical.fill", defaultValue: "本棚(塗り)")),
            IconItem(name: "book.pages", label: String(localized: "symbolPicker.icon.book.pages", defaultValue: "ページ")),
            IconItem(name: "book.pages.fill", label: String(localized: "symbolPicker.icon.book.pages.fill", defaultValue: "ページ(塗り)")),
            IconItem(name: "text.book.closed", label: String(localized: "symbolPicker.icon.text.book.closed", defaultValue: "教科書")),
            IconItem(name: "text.book.closed.fill", label: String(localized: "symbolPicker.icon.text.book.closed.fill", defaultValue: "教科書(塗り)")),
            IconItem(name: "character.book.closed", label: String(localized: "symbolPicker.icon.character.book.closed", defaultValue: "辞書")),
            IconItem(name: "character.book.closed.fill", label: String(localized: "symbolPicker.icon.character.book.closed.fill", defaultValue: "辞書(塗り)")),
            IconItem(name: "graduationcap", label: String(localized: "symbolPicker.icon.graduationcap", defaultValue: "卒業帽")),
            IconItem(name: "graduationcap.fill", label: String(localized: "symbolPicker.icon.graduationcap.fill", defaultValue: "卒業帽(塗り)")),
            IconItem(name: "pencil", label: String(localized: "symbolPicker.icon.pencil", defaultValue: "鉛筆")),
            IconItem(name: "pencil.circle", label: String(localized: "symbolPicker.icon.pencil.circle", defaultValue: "鉛筆(丸)")),
            IconItem(name: "pencil.and.ruler", label: String(localized: "symbolPicker.icon.pencil.and.ruler", defaultValue: "鉛筆と定規")),
            IconItem(name: "pencil.and.ruler.fill", label: String(localized: "symbolPicker.icon.pencil.and.ruler.fill", defaultValue: "鉛筆と定規(塗り)")),
            IconItem(name: "ruler", label: String(localized: "symbolPicker.icon.ruler", defaultValue: "定規")),
            IconItem(name: "ruler.fill", label: String(localized: "symbolPicker.icon.ruler.fill", defaultValue: "定規(塗り)")),
            IconItem(name: "highlighter", label: String(localized: "symbolPicker.icon.highlighter", defaultValue: "蛍光ペン")),
            IconItem(name: "lightbulb", label: String(localized: "symbolPicker.icon.lightbulb", defaultValue: "電球")),
            IconItem(name: "lightbulb.fill", label: String(localized: "symbolPicker.icon.lightbulb.fill", defaultValue: "電球(塗り)")),
            IconItem(name: "brain", label: String(localized: "symbolPicker.icon.brain", defaultValue: "脳")),
            IconItem(name: "brain.fill", label: String(localized: "symbolPicker.icon.brain.fill", defaultValue: "脳(塗り)")),
            IconItem(name: "brain.head.profile", label: String(localized: "symbolPicker.icon.brain.head.profile", defaultValue: "脳(横顔)")),
            IconItem(name: "quote.opening", label: String(localized: "symbolPicker.icon.quote.opening", defaultValue: "引用開始")),
            IconItem(name: "quote.closing", label: String(localized: "symbolPicker.icon.quote.closing", defaultValue: "引用終了")),
            IconItem(name: "quote.bubble", label: String(localized: "symbolPicker.icon.quote.bubble", defaultValue: "引用吹き出し")),
            IconItem(name: "quote.bubble.fill", label: String(localized: "symbolPicker.icon.quote.bubble.fill", defaultValue: "引用吹き出し(塗り)")),
            IconItem(name: "text.bubble", label: String(localized: "symbolPicker.icon.text.bubble", defaultValue: "テキスト吹き出し")),
            IconItem(name: "text.bubble.fill", label: String(localized: "symbolPicker.icon.text.bubble.fill", defaultValue: "テキスト吹き出し(塗り)")),
            IconItem(name: "globe", label: String(localized: "symbolPicker.icon.globe", defaultValue: "地球儀")),
            IconItem(name: "globe.americas", label: String(localized: "symbolPicker.icon.globe.americas", defaultValue: "地球儀(南北米)")),
            IconItem(name: "globe.asia.australia", label: String(localized: "symbolPicker.icon.globe.asia.australia", defaultValue: "地球儀(アジア)")),
            IconItem(name: "globe.europe.africa", label: String(localized: "symbolPicker.icon.globe.europe.africa", defaultValue: "地球儀(欧州)")),
            IconItem(name: "atom", label: String(localized: "symbolPicker.icon.atom", defaultValue: "原子")),
            IconItem(name: "function", label: String(localized: "symbolPicker.icon.function", defaultValue: "関数")),
            IconItem(name: "testtube.2", label: String(localized: "symbolPicker.icon.testtube.2", defaultValue: "試験管")),
            IconItem(name: "flask", label: String(localized: "symbolPicker.icon.flask", defaultValue: "フラスコ")),
            IconItem(name: "flask.fill", label: String(localized: "symbolPicker.icon.flask.fill", defaultValue: "フラスコ(塗り)")),
            IconItem(name: "microscope", label: String(localized: "symbolPicker.icon.microscope", defaultValue: "顕微鏡")),
            IconItem(name: "stethoscope", label: String(localized: "symbolPicker.icon.stethoscope", defaultValue: "聴診器")),
            IconItem(name: "backpack", label: String(localized: "symbolPicker.icon.backpack", defaultValue: "リュック")),
            IconItem(name: "backpack.fill", label: String(localized: "symbolPicker.icon.backpack.fill", defaultValue: "リュック(塗り)")),
            IconItem(name: "studentdesk", label: String(localized: "symbolPicker.icon.studentdesk", defaultValue: "学習机")),
            IconItem(name: "doc.text.magnifyingglass", label: String(localized: "symbolPicker.icon.doc.text.magnifyingglass", defaultValue: "文書検索")),
            IconItem(name: "note.text.badge.plus", label: String(localized: "symbolPicker.icon.note.text.badge.plus", defaultValue: "ノート追加")),
            IconItem(name: "pencil.and.list.clipboard", label: String(localized: "symbolPicker.icon.pencil.and.list.clipboard", defaultValue: "学習記録")),
            IconItem(name: "scribble", label: String(localized: "symbolPicker.icon.scribble", defaultValue: "手書き")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 4. 食べ物・飲み物 (Food & Drink)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.foodDrink", defaultValue: "食べ物・飲み物"), icons: [
            IconItem(name: "fork.knife", label: String(localized: "symbolPicker.icon.fork.knife", defaultValue: "食事")),
            IconItem(name: "fork.knife.circle", label: String(localized: "symbolPicker.icon.fork.knife.circle", defaultValue: "食事(丸)")),
            IconItem(name: "fork.knife.circle.fill", label: String(localized: "symbolPicker.icon.fork.knife.circle.fill", defaultValue: "食事(丸塗り)")),
            IconItem(name: "cup.and.saucer", label: String(localized: "symbolPicker.icon.cup.and.saucer", defaultValue: "コーヒー")),
            IconItem(name: "cup.and.saucer.fill", label: String(localized: "symbolPicker.icon.cup.and.saucer.fill", defaultValue: "コーヒー(塗り)")),
            IconItem(name: "mug", label: String(localized: "symbolPicker.icon.mug", defaultValue: "マグカップ")),
            IconItem(name: "mug.fill", label: String(localized: "symbolPicker.icon.mug.fill", defaultValue: "マグカップ(塗り)")),
            IconItem(name: "wineglass", label: String(localized: "symbolPicker.icon.wineglass", defaultValue: "ワイングラス")),
            IconItem(name: "wineglass.fill", label: String(localized: "symbolPicker.icon.wineglass.fill", defaultValue: "ワイングラス(塗り)")),
            IconItem(name: "waterbottle", label: String(localized: "symbolPicker.icon.waterbottle", defaultValue: "水筒")),
            IconItem(name: "waterbottle.fill", label: String(localized: "symbolPicker.icon.waterbottle.fill", defaultValue: "水筒(塗り)")),
            IconItem(name: "takeoutbag.and.cup.and.straw", label: String(localized: "symbolPicker.icon.takeoutbag.and.cup.and.straw", defaultValue: "テイクアウト")),
            IconItem(name: "takeoutbag.and.cup.and.straw.fill", label: String(localized: "symbolPicker.icon.takeoutbag.and.cup.and.straw.fill", defaultValue: "テイクアウト(塗り)")),
            IconItem(name: "birthday.cake", label: String(localized: "symbolPicker.icon.birthday.cake", defaultValue: "ケーキ")),
            IconItem(name: "birthday.cake.fill", label: String(localized: "symbolPicker.icon.birthday.cake.fill", defaultValue: "ケーキ(塗り)")),
            IconItem(name: "carrot", label: String(localized: "symbolPicker.icon.carrot", defaultValue: "にんじん")),
            IconItem(name: "carrot.fill", label: String(localized: "symbolPicker.icon.carrot.fill", defaultValue: "にんじん(塗り)")),
            IconItem(name: "leaf", label: String(localized: "symbolPicker.icon.leaf", defaultValue: "葉っぱ")),
            IconItem(name: "leaf.fill", label: String(localized: "symbolPicker.icon.leaf.fill", defaultValue: "葉っぱ(塗り)")),
            IconItem(name: "flame", label: String(localized: "symbolPicker.icon.flame", defaultValue: "炎")),
            IconItem(name: "flame.fill", label: String(localized: "symbolPicker.icon.flame.fill", defaultValue: "炎(塗り)")),
            IconItem(name: "frying.pan", label: String(localized: "symbolPicker.icon.frying.pan", defaultValue: "フライパン")),
            IconItem(name: "frying.pan.fill", label: String(localized: "symbolPicker.icon.frying.pan.fill", defaultValue: "フライパン(塗り)")),
            IconItem(name: "oven", label: String(localized: "symbolPicker.icon.oven", defaultValue: "オーブン")),
            IconItem(name: "oven.fill", label: String(localized: "symbolPicker.icon.oven.fill", defaultValue: "オーブン(塗り)")),
            IconItem(name: "cooktop", label: String(localized: "symbolPicker.icon.cooktop", defaultValue: "コンロ")),
            IconItem(name: "cooktop.fill", label: String(localized: "symbolPicker.icon.cooktop.fill", defaultValue: "コンロ(塗り)")),
            IconItem(name: "basket", label: String(localized: "symbolPicker.icon.basket", defaultValue: "バスケット")),
            IconItem(name: "basket.fill", label: String(localized: "symbolPicker.icon.basket.fill", defaultValue: "バスケット(塗り)")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 5. ショッピング・ファッション (Shopping & Fashion)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.shopping", defaultValue: "ショッピング"), icons: [
            IconItem(name: "cart", label: String(localized: "symbolPicker.icon.cart", defaultValue: "カート")),
            IconItem(name: "cart.fill", label: String(localized: "symbolPicker.icon.cart.fill", defaultValue: "カート(塗り)")),
            IconItem(name: "cart.badge.plus", label: String(localized: "symbolPicker.icon.cart.badge.plus", defaultValue: "カート追加")),
            IconItem(name: "cart.badge.minus", label: String(localized: "symbolPicker.icon.cart.badge.minus", defaultValue: "カート削除")),
            IconItem(name: "bag", label: String(localized: "symbolPicker.icon.bag", defaultValue: "ショッピングバッグ")),
            IconItem(name: "bag.fill", label: String(localized: "symbolPicker.icon.bag.fill", defaultValue: "ショッピングバッグ(塗り)")),
            IconItem(name: "bag.badge.plus", label: String(localized: "symbolPicker.icon.bag.badge.plus", defaultValue: "バッグ追加")),
            IconItem(name: "bag.badge.minus", label: String(localized: "symbolPicker.icon.bag.badge.minus", defaultValue: "バッグ削除")),
            IconItem(name: "handbag", label: String(localized: "symbolPicker.icon.handbag", defaultValue: "ハンドバッグ")),
            IconItem(name: "handbag.fill", label: String(localized: "symbolPicker.icon.handbag.fill", defaultValue: "ハンドバッグ(塗り)")),
            IconItem(name: "gift", label: String(localized: "symbolPicker.icon.gift", defaultValue: "ギフト")),
            IconItem(name: "gift.fill", label: String(localized: "symbolPicker.icon.gift.fill", defaultValue: "ギフト(塗り)")),
            IconItem(name: "gift.circle", label: String(localized: "symbolPicker.icon.gift.circle", defaultValue: "ギフト(丸)")),
            IconItem(name: "gift.circle.fill", label: String(localized: "symbolPicker.icon.gift.circle.fill", defaultValue: "ギフト(丸塗り)")),
            IconItem(name: "giftcard", label: String(localized: "symbolPicker.icon.giftcard", defaultValue: "ギフトカード")),
            IconItem(name: "giftcard.fill", label: String(localized: "symbolPicker.icon.giftcard.fill", defaultValue: "ギフトカード(塗り)")),
            IconItem(name: "tshirt", label: String(localized: "symbolPicker.icon.tshirt", defaultValue: "Tシャツ")),
            IconItem(name: "tshirt.fill", label: String(localized: "symbolPicker.icon.tshirt.fill", defaultValue: "Tシャツ(塗り)")),
            IconItem(name: "shoe", label: String(localized: "symbolPicker.icon.shoe", defaultValue: "靴")),
            IconItem(name: "shoe.fill", label: String(localized: "symbolPicker.icon.shoe.fill", defaultValue: "靴(塗り)")),
            IconItem(name: "shoe.2", label: String(localized: "symbolPicker.icon.shoe.2", defaultValue: "靴ペア")),
            IconItem(name: "shoe.2.fill", label: String(localized: "symbolPicker.icon.shoe.2.fill", defaultValue: "靴ペア(塗り)")),
            IconItem(name: "eyeglasses", label: String(localized: "symbolPicker.icon.eyeglasses", defaultValue: "メガネ")),
            IconItem(name: "watch.analog", label: String(localized: "symbolPicker.icon.watch.analog", defaultValue: "腕時計")),
            IconItem(name: "crown", label: String(localized: "symbolPicker.icon.crown", defaultValue: "王冠")),
            IconItem(name: "crown.fill", label: String(localized: "symbolPicker.icon.crown.fill", defaultValue: "王冠(塗り)")),
            IconItem(name: "sparkles", label: String(localized: "symbolPicker.icon.sparkles", defaultValue: "キラキラ")),
            IconItem(name: "barcode", label: String(localized: "symbolPicker.icon.barcode", defaultValue: "バーコード")),
            IconItem(name: "barcode.viewfinder", label: String(localized: "symbolPicker.icon.barcode.viewfinder", defaultValue: "バーコードスキャン")),
            IconItem(name: "scissors", label: String(localized: "symbolPicker.icon.scissors", defaultValue: "ハサミ")),
            IconItem(name: "hanger", label: String(localized: "symbolPicker.icon.hanger", defaultValue: "ハンガー")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 6. 旅行・場所 (Travel & Places)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.travelPlaces", defaultValue: "旅行・場所"), icons: [
            IconItem(name: "airplane", label: String(localized: "symbolPicker.icon.airplane", defaultValue: "飛行機")),
            IconItem(name: "airplane.departure", label: String(localized: "symbolPicker.icon.airplane.departure", defaultValue: "出発")),
            IconItem(name: "airplane.arrival", label: String(localized: "symbolPicker.icon.airplane.arrival", defaultValue: "到着")),
            IconItem(name: "car", label: String(localized: "symbolPicker.icon.car", defaultValue: "車")),
            IconItem(name: "car.fill", label: String(localized: "symbolPicker.icon.car.fill", defaultValue: "車(塗り)")),
            IconItem(name: "car.side", label: String(localized: "symbolPicker.icon.car.side", defaultValue: "車(横)")),
            IconItem(name: "car.side.fill", label: String(localized: "symbolPicker.icon.car.side.fill", defaultValue: "車(横塗り)")),
            IconItem(name: "bus", label: String(localized: "symbolPicker.icon.bus", defaultValue: "バス")),
            IconItem(name: "bus.fill", label: String(localized: "symbolPicker.icon.bus.fill", defaultValue: "バス(塗り)")),
            IconItem(name: "bus.doubledecker", label: String(localized: "symbolPicker.icon.bus.doubledecker", defaultValue: "二階建てバス")),
            IconItem(name: "bus.doubledecker.fill", label: String(localized: "symbolPicker.icon.bus.doubledecker.fill", defaultValue: "二階建てバス(塗り)")),
            IconItem(name: "tram", label: String(localized: "symbolPicker.icon.tram", defaultValue: "路面電車")),
            IconItem(name: "tram.fill", label: String(localized: "symbolPicker.icon.tram.fill", defaultValue: "路面電車(塗り)")),
            IconItem(name: "train.side.front.car", label: String(localized: "symbolPicker.icon.train.side.front.car", defaultValue: "電車")),
            IconItem(name: "ferry", label: String(localized: "symbolPicker.icon.ferry", defaultValue: "フェリー")),
            IconItem(name: "ferry.fill", label: String(localized: "symbolPicker.icon.ferry.fill", defaultValue: "フェリー(塗り)")),
            IconItem(name: "bicycle", label: String(localized: "symbolPicker.icon.bicycle", defaultValue: "自転車")),
            IconItem(name: "scooter", label: String(localized: "symbolPicker.icon.scooter", defaultValue: "スクーター")),
            IconItem(name: "fuelpump", label: String(localized: "symbolPicker.icon.fuelpump", defaultValue: "ガソリンスタンド")),
            IconItem(name: "fuelpump.fill", label: String(localized: "symbolPicker.icon.fuelpump.fill", defaultValue: "ガソリンスタンド(塗り)")),
            IconItem(name: "mappin", label: String(localized: "symbolPicker.icon.mappin", defaultValue: "マップピン")),
            IconItem(name: "mappin.circle", label: String(localized: "symbolPicker.icon.mappin.circle", defaultValue: "マップピン(丸)")),
            IconItem(name: "mappin.circle.fill", label: String(localized: "symbolPicker.icon.mappin.circle.fill", defaultValue: "マップピン(丸塗り)")),
            IconItem(name: "mappin.and.ellipse", label: String(localized: "symbolPicker.icon.mappin.and.ellipse", defaultValue: "マップピン(影)")),
            IconItem(name: "mappin.slash", label: String(localized: "symbolPicker.icon.mappin.slash", defaultValue: "マップピンオフ")),
            IconItem(name: "map", label: String(localized: "symbolPicker.icon.map", defaultValue: "地図")),
            IconItem(name: "map.fill", label: String(localized: "symbolPicker.icon.map.fill", defaultValue: "地図(塗り)")),
            IconItem(name: "map.circle", label: String(localized: "symbolPicker.icon.map.circle", defaultValue: "地図(丸)")),
            IconItem(name: "location", label: String(localized: "symbolPicker.icon.location", defaultValue: "位置情報")),
            IconItem(name: "location.fill", label: String(localized: "symbolPicker.icon.location.fill", defaultValue: "位置情報(塗り)")),
            IconItem(name: "location.circle", label: String(localized: "symbolPicker.icon.location.circle", defaultValue: "位置情報(丸)")),
            IconItem(name: "mountain.2", label: String(localized: "symbolPicker.icon.mountain.2", defaultValue: "山")),
            IconItem(name: "mountain.2.fill", label: String(localized: "symbolPicker.icon.mountain.2.fill", defaultValue: "山(塗り)")),
            IconItem(name: "house", label: String(localized: "symbolPicker.icon.house", defaultValue: "家")),
            IconItem(name: "house.fill", label: String(localized: "symbolPicker.icon.house.fill", defaultValue: "家(塗り)")),
            IconItem(name: "house.lodge", label: String(localized: "symbolPicker.icon.house.lodge", defaultValue: "ロッジ")),
            IconItem(name: "house.lodge.fill", label: String(localized: "symbolPicker.icon.house.lodge.fill", defaultValue: "ロッジ(塗り)")),
            IconItem(name: "bed.double", label: String(localized: "symbolPicker.icon.bed.double", defaultValue: "ベッド")),
            IconItem(name: "bed.double.fill", label: String(localized: "symbolPicker.icon.bed.double.fill", defaultValue: "ベッド(塗り)")),
            IconItem(name: "tent", label: String(localized: "symbolPicker.icon.tent", defaultValue: "テント")),
            IconItem(name: "tent.fill", label: String(localized: "symbolPicker.icon.tent.fill", defaultValue: "テント(塗り)")),
            IconItem(name: "tent.2", label: String(localized: "symbolPicker.icon.tent.2", defaultValue: "テント群")),
            IconItem(name: "tent.2.fill", label: String(localized: "symbolPicker.icon.tent.2.fill", defaultValue: "テント群(塗り)")),
            IconItem(name: "beach.umbrella", label: String(localized: "symbolPicker.icon.beach.umbrella", defaultValue: "ビーチ")),
            IconItem(name: "beach.umbrella.fill", label: String(localized: "symbolPicker.icon.beach.umbrella.fill", defaultValue: "ビーチ(塗り)")),
            IconItem(name: "suitcase", label: String(localized: "symbolPicker.icon.suitcase", defaultValue: "スーツケース")),
            IconItem(name: "suitcase.fill", label: String(localized: "symbolPicker.icon.suitcase.fill", defaultValue: "スーツケース(塗り)")),
            IconItem(name: "suitcase.rolling", label: String(localized: "symbolPicker.icon.suitcase.rolling", defaultValue: "キャリーケース")),
            IconItem(name: "suitcase.rolling.fill", label: String(localized: "symbolPicker.icon.suitcase.rolling.fill", defaultValue: "キャリーケース(塗り)")),
            IconItem(name: "binoculars", label: String(localized: "symbolPicker.icon.binoculars", defaultValue: "双眼鏡")),
            IconItem(name: "binoculars.fill", label: String(localized: "symbolPicker.icon.binoculars.fill", defaultValue: "双眼鏡(塗り)")),
            IconItem(name: "figure.hiking", label: String(localized: "symbolPicker.icon.figure.hiking", defaultValue: "ハイキング")),
            IconItem(name: "figure.walk", label: String(localized: "symbolPicker.icon.figure.walk", defaultValue: "徒歩")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 7. エンタメ・メディア (Entertainment & Media)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.entertainment", defaultValue: "エンタメ"), icons: [
            IconItem(name: "play", label: String(localized: "symbolPicker.icon.play", defaultValue: "再生")),
            IconItem(name: "play.fill", label: String(localized: "symbolPicker.icon.play.fill", defaultValue: "再生(塗り)")),
            IconItem(name: "play.circle", label: String(localized: "symbolPicker.icon.play.circle", defaultValue: "再生(丸)")),
            IconItem(name: "play.circle.fill", label: String(localized: "symbolPicker.icon.play.circle.fill", defaultValue: "再生(丸塗り)")),
            IconItem(name: "pause", label: String(localized: "symbolPicker.icon.pause", defaultValue: "一時停止")),
            IconItem(name: "pause.fill", label: String(localized: "symbolPicker.icon.pause.fill", defaultValue: "一時停止(塗り)")),
            IconItem(name: "music.note", label: String(localized: "symbolPicker.icon.music.note", defaultValue: "音符")),
            IconItem(name: "music.note.list", label: String(localized: "symbolPicker.icon.music.note.list", defaultValue: "プレイリスト")),
            IconItem(name: "music.quarternote.3", label: String(localized: "symbolPicker.icon.music.quarternote.3", defaultValue: "三連符")),
            IconItem(name: "music.mic", label: String(localized: "symbolPicker.icon.music.mic", defaultValue: "カラオケ")),
            IconItem(name: "headphones", label: String(localized: "symbolPicker.icon.headphones", defaultValue: "ヘッドホン")),
            IconItem(name: "headphones.circle", label: String(localized: "symbolPicker.icon.headphones.circle", defaultValue: "ヘッドホン(丸)")),
            IconItem(name: "headphones.circle.fill", label: String(localized: "symbolPicker.icon.headphones.circle.fill", defaultValue: "ヘッドホン(丸塗り)")),
            IconItem(name: "airpods", label: String(localized: "symbolPicker.icon.airpods", defaultValue: "イヤホン")),
            IconItem(name: "airpodspro", label: String(localized: "symbolPicker.icon.airpodspro", defaultValue: "ワイヤレスイヤホン")),
            IconItem(name: "speaker", label: String(localized: "symbolPicker.icon.speaker", defaultValue: "スピーカー")),
            IconItem(name: "speaker.fill", label: String(localized: "symbolPicker.icon.speaker.fill", defaultValue: "スピーカー(塗り)")),
            IconItem(name: "speaker.wave.2", label: String(localized: "symbolPicker.icon.speaker.wave.2", defaultValue: "スピーカー(音量)")),
            IconItem(name: "speaker.wave.2.fill", label: String(localized: "symbolPicker.icon.speaker.wave.2.fill", defaultValue: "スピーカー(音量塗り)")),
            IconItem(name: "speaker.slash", label: String(localized: "symbolPicker.icon.speaker.slash", defaultValue: "ミュート")),
            IconItem(name: "mic", label: String(localized: "symbolPicker.icon.mic", defaultValue: "マイク")),
            IconItem(name: "mic.fill", label: String(localized: "symbolPicker.icon.mic.fill", defaultValue: "マイク(塗り)")),
            IconItem(name: "mic.slash", label: String(localized: "symbolPicker.icon.mic.slash", defaultValue: "マイクオフ")),
            IconItem(name: "film", label: String(localized: "symbolPicker.icon.film", defaultValue: "フィルム")),
            IconItem(name: "film.fill", label: String(localized: "symbolPicker.icon.film.fill", defaultValue: "フィルム(塗り)")),
            IconItem(name: "film.stack", label: String(localized: "symbolPicker.icon.film.stack", defaultValue: "フィルム(重ね)")),
            IconItem(name: "film.stack.fill", label: String(localized: "symbolPicker.icon.film.stack.fill", defaultValue: "フィルム(重ね塗り)")),
            IconItem(name: "popcorn", label: String(localized: "symbolPicker.icon.popcorn", defaultValue: "ポップコーン")),
            IconItem(name: "popcorn.fill", label: String(localized: "symbolPicker.icon.popcorn.fill", defaultValue: "ポップコーン(塗り)")),
            IconItem(name: "tv", label: String(localized: "symbolPicker.icon.tv", defaultValue: "テレビ")),
            IconItem(name: "tv.fill", label: String(localized: "symbolPicker.icon.tv.fill", defaultValue: "テレビ(塗り)")),
            IconItem(name: "gamecontroller", label: String(localized: "symbolPicker.icon.gamecontroller", defaultValue: "ゲームコントローラ")),
            IconItem(name: "gamecontroller.fill", label: String(localized: "symbolPicker.icon.gamecontroller.fill", defaultValue: "ゲームコントローラ(塗り)")),
            IconItem(name: "theatermasks", label: String(localized: "symbolPicker.icon.theatermasks", defaultValue: "演劇マスク")),
            IconItem(name: "theatermasks.fill", label: String(localized: "symbolPicker.icon.theatermasks.fill", defaultValue: "演劇マスク(塗り)")),
            IconItem(name: "ticket", label: String(localized: "symbolPicker.icon.ticket", defaultValue: "チケット")),
            IconItem(name: "ticket.fill", label: String(localized: "symbolPicker.icon.ticket.fill", defaultValue: "チケット(塗り)")),
            IconItem(name: "party.popper", label: String(localized: "symbolPicker.icon.party.popper", defaultValue: "パーティー")),
            IconItem(name: "party.popper.fill", label: String(localized: "symbolPicker.icon.party.popper.fill", defaultValue: "パーティー(塗り)")),
            IconItem(name: "dice", label: String(localized: "symbolPicker.icon.dice", defaultValue: "サイコロ")),
            IconItem(name: "dice.fill", label: String(localized: "symbolPicker.icon.dice.fill", defaultValue: "サイコロ(塗り)")),
            IconItem(name: "puzzlepiece", label: String(localized: "symbolPicker.icon.puzzlepiece", defaultValue: "パズル")),
            IconItem(name: "puzzlepiece.fill", label: String(localized: "symbolPicker.icon.puzzlepiece.fill", defaultValue: "パズル(塗り)")),
            IconItem(name: "guitars", label: String(localized: "symbolPicker.icon.guitars", defaultValue: "ギター")),
            IconItem(name: "guitars.fill", label: String(localized: "symbolPicker.icon.guitars.fill", defaultValue: "ギター(塗り)")),
            IconItem(name: "pianokeys", label: String(localized: "symbolPicker.icon.pianokeys", defaultValue: "ピアノ")),
            IconItem(name: "pianokeys.inverse", label: String(localized: "symbolPicker.icon.pianokeys.inverse", defaultValue: "ピアノ(反転)")),
            IconItem(name: "video", label: String(localized: "symbolPicker.icon.video", defaultValue: "ビデオ")),
            IconItem(name: "video.fill", label: String(localized: "symbolPicker.icon.video.fill", defaultValue: "ビデオ(塗り)")),
            IconItem(name: "video.circle", label: String(localized: "symbolPicker.icon.video.circle", defaultValue: "ビデオ(丸)")),
            IconItem(name: "video.circle.fill", label: String(localized: "symbolPicker.icon.video.circle.fill", defaultValue: "ビデオ(丸塗り)")),
            IconItem(name: "trophy", label: String(localized: "symbolPicker.icon.trophy", defaultValue: "トロフィー")),
            IconItem(name: "trophy.fill", label: String(localized: "symbolPicker.icon.trophy.fill", defaultValue: "トロフィー(塗り)")),
            IconItem(name: "medal", label: String(localized: "symbolPicker.icon.medal", defaultValue: "メダル")),
            IconItem(name: "medal.fill", label: String(localized: "symbolPicker.icon.medal.fill", defaultValue: "メダル(塗り)")),
            IconItem(name: "rosette", label: String(localized: "symbolPicker.icon.rosette", defaultValue: "ロゼット")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 8. 写真・アート・デザイン (Photo/Art/Design)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.photoArt", defaultValue: "写真・アート"), icons: [
            IconItem(name: "camera", label: String(localized: "symbolPicker.icon.camera", defaultValue: "カメラ")),
            IconItem(name: "camera.fill", label: String(localized: "symbolPicker.icon.camera.fill", defaultValue: "カメラ(塗り)")),
            IconItem(name: "camera.circle", label: String(localized: "symbolPicker.icon.camera.circle", defaultValue: "カメラ丸")),
            IconItem(name: "camera.aperture", label: String(localized: "symbolPicker.icon.camera.aperture", defaultValue: "絞り")),
            IconItem(name: "camera.filters", label: String(localized: "symbolPicker.icon.camera.filters", defaultValue: "カメラフィルター")),
            IconItem(name: "camera.macro", label: String(localized: "symbolPicker.icon.camera.macro", defaultValue: "マクロ撮影")),
            IconItem(name: "camera.shutter.button", label: String(localized: "symbolPicker.icon.camera.shutter.button", defaultValue: "シャッターボタン")),
            IconItem(name: "camera.viewfinder", label: String(localized: "symbolPicker.icon.camera.viewfinder", defaultValue: "ファインダー")),
            IconItem(name: "camera.on.rectangle", label: String(localized: "symbolPicker.icon.camera.on.rectangle", defaultValue: "画面上カメラ")),
            IconItem(name: "photo", label: String(localized: "symbolPicker.icon.photo", defaultValue: "写真")),
            IconItem(name: "photo.fill", label: String(localized: "symbolPicker.icon.photo.fill", defaultValue: "写真(塗り)")),
            IconItem(name: "photo.artframe", label: String(localized: "symbolPicker.icon.photo.artframe", defaultValue: "額縁写真")),
            IconItem(name: "photo.badge.plus", label: String(localized: "symbolPicker.icon.photo.badge.plus", defaultValue: "写真追加")),
            IconItem(name: "photo.on.rectangle.angled", label: String(localized: "symbolPicker.icon.photo.on.rectangle.angled", defaultValue: "重ね写真")),
            IconItem(name: "photo.stack", label: String(localized: "symbolPicker.icon.photo.stack", defaultValue: "写真スタック")),
            IconItem(name: "photo.stack.fill", label: String(localized: "symbolPicker.icon.photo.stack.fill", defaultValue: "写真スタック(塗り)")),
            IconItem(name: "paintbrush", label: String(localized: "symbolPicker.icon.paintbrush", defaultValue: "絵筆")),
            IconItem(name: "paintbrush.fill", label: String(localized: "symbolPicker.icon.paintbrush.fill", defaultValue: "絵筆(塗り)")),
            IconItem(name: "paintbrush.pointed", label: String(localized: "symbolPicker.icon.paintbrush.pointed", defaultValue: "尖った絵筆")),
            IconItem(name: "paintbrush.pointed.fill", label: String(localized: "symbolPicker.icon.paintbrush.pointed.fill", defaultValue: "尖った絵筆(塗り)")),
            IconItem(name: "paintpalette", label: String(localized: "symbolPicker.icon.paintpalette", defaultValue: "パレット")),
            IconItem(name: "paintpalette.fill", label: String(localized: "symbolPicker.icon.paintpalette.fill", defaultValue: "パレット(塗り)")),
            IconItem(name: "pencil.tip", label: String(localized: "symbolPicker.icon.pencil.tip", defaultValue: "ペン先")),
            IconItem(name: "pencil.and.outline", label: String(localized: "symbolPicker.icon.pencil.and.outline", defaultValue: "鉛筆とアウトライン")),
            IconItem(name: "pencil.and.scribble", label: String(localized: "symbolPicker.icon.pencil.and.scribble", defaultValue: "鉛筆と落書き")),
            IconItem(name: "scribble.variable", label: String(localized: "symbolPicker.icon.scribble.variable", defaultValue: "落書き(可変)")),
            IconItem(name: "wand.and.stars", label: String(localized: "symbolPicker.icon.wand.and.stars", defaultValue: "魔法の杖")),
            IconItem(name: "wand.and.rays", label: String(localized: "symbolPicker.icon.wand.and.rays", defaultValue: "杖と光線")),
            IconItem(name: "crop", label: String(localized: "symbolPicker.icon.crop", defaultValue: "トリミング")),
            IconItem(name: "crop.rotate", label: String(localized: "symbolPicker.icon.crop.rotate", defaultValue: "トリミング回転")),
            IconItem(name: "eyedropper", label: String(localized: "symbolPicker.icon.eyedropper", defaultValue: "スポイト")),
            IconItem(name: "eyedropper.halffull", label: String(localized: "symbolPicker.icon.eyedropper.halffull", defaultValue: "スポイト(半分)")),
            IconItem(name: "eyedropper.full", label: String(localized: "symbolPicker.icon.eyedropper.full", defaultValue: "スポイト(満杯)")),
            IconItem(name: "lasso", label: String(localized: "symbolPicker.icon.lasso", defaultValue: "なげなわ")),
            IconItem(name: "lasso.and.sparkles", label: String(localized: "symbolPicker.icon.lasso.and.sparkles", defaultValue: "なげなわとキラキラ")),
            IconItem(name: "rectangle.3.group", label: String(localized: "symbolPicker.icon.rectangle.3.group", defaultValue: "矩形グループ")),
            IconItem(name: "swatchpalette", label: String(localized: "symbolPicker.icon.swatchpalette", defaultValue: "色見本")),
            IconItem(name: "mosaic", label: String(localized: "symbolPicker.icon.mosaic", defaultValue: "モザイク")),
            IconItem(name: "square.grid.3x3", label: String(localized: "symbolPicker.icon.square.grid.3x3", defaultValue: "3x3グリッド")),
            IconItem(name: "rotate.3d", label: String(localized: "symbolPicker.icon.rotate.3d", defaultValue: "3D回転")),
            IconItem(name: "move.3d", label: String(localized: "symbolPicker.icon.move.3d", defaultValue: "3D移動")),
            IconItem(name: "scale.3d", label: String(localized: "symbolPicker.icon.scale.3d", defaultValue: "3Dスケール")),
            IconItem(name: "skew", label: String(localized: "symbolPicker.icon.skew", defaultValue: "傾斜")),
            IconItem(name: "perspective", label: String(localized: "symbolPicker.icon.perspective", defaultValue: "遠近法")),
            IconItem(name: "square.on.square", label: String(localized: "symbolPicker.icon.square.on.square", defaultValue: "正方形重ね")),
            IconItem(name: "rectangle.on.rectangle", label: String(localized: "symbolPicker.icon.rectangle.on.rectangle", defaultValue: "矩形重ね")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 9. テクノロジー・デバイス (Technology/Devices)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.technology", defaultValue: "テクノロジー"), icons: [
            IconItem(name: "laptopcomputer", label: String(localized: "symbolPicker.icon.laptopcomputer", defaultValue: "ノートPC")),
            IconItem(name: "desktopcomputer", label: String(localized: "symbolPicker.icon.desktopcomputer", defaultValue: "デスクトップPC")),
            IconItem(name: "display", label: String(localized: "symbolPicker.icon.display", defaultValue: "ディスプレイ")),
            IconItem(name: "iphone", label: String(localized: "symbolPicker.icon.iphone", defaultValue: "iPhone")),
            IconItem(name: "ipad", label: String(localized: "symbolPicker.icon.ipad", defaultValue: "iPad")),
            IconItem(name: "applewatch", label: String(localized: "symbolPicker.icon.applewatch", defaultValue: "Apple Watch")),
            IconItem(name: "visionpro", label: String(localized: "symbolPicker.icon.visionpro", defaultValue: "Vision Pro")),
            IconItem(name: "appletv", label: String(localized: "symbolPicker.icon.appletv", defaultValue: "Apple TV")),
            IconItem(name: "homepod", label: String(localized: "symbolPicker.icon.homepod", defaultValue: "HomePod")),
            IconItem(name: "keyboard", label: String(localized: "symbolPicker.icon.keyboard", defaultValue: "キーボード")),
            IconItem(name: "computermouse", label: String(localized: "symbolPicker.icon.computermouse", defaultValue: "マウス")),
            IconItem(name: "cpu", label: String(localized: "symbolPicker.icon.cpu", defaultValue: "CPU")),
            IconItem(name: "memorychip", label: String(localized: "symbolPicker.icon.memorychip", defaultValue: "メモリチップ")),
            IconItem(name: "server.rack", label: String(localized: "symbolPicker.icon.server.rack", defaultValue: "サーバーラック")),
            IconItem(name: "externaldrive", label: String(localized: "symbolPicker.icon.externaldrive", defaultValue: "外付けドライブ")),
            IconItem(name: "scanner", label: String(localized: "symbolPicker.icon.scanner", defaultValue: "スキャナー")),
            IconItem(name: "wifi", label: String(localized: "symbolPicker.icon.wifi", defaultValue: "Wi-Fi")),
            IconItem(name: "antenna.radiowaves.left.and.right", label: String(localized: "symbolPicker.icon.antenna.radiowaves.left.and.right", defaultValue: "アンテナ電波")),
            IconItem(name: "bolt", label: String(localized: "symbolPicker.icon.bolt", defaultValue: "電気")),
            IconItem(name: "terminal", label: String(localized: "symbolPicker.icon.terminal", defaultValue: "ターミナル")),
            IconItem(name: "chevron.left.forwardslash.chevron.right", label: String(localized: "symbolPicker.icon.chevron.left.forwardslash.chevron.right", defaultValue: "コード")),
            IconItem(name: "wrench", label: String(localized: "symbolPicker.icon.wrench", defaultValue: "レンチ")),
            IconItem(name: "wrench.and.screwdriver", label: String(localized: "symbolPicker.icon.wrench.and.screwdriver", defaultValue: "工具")),
            IconItem(name: "gearshape.2", label: String(localized: "symbolPicker.icon.gearshape.2", defaultValue: "歯車2つ")),
            IconItem(name: "qrcode", label: String(localized: "symbolPicker.icon.qrcode", defaultValue: "QRコード")),
            IconItem(name: "qrcode.viewfinder", label: String(localized: "symbolPicker.icon.qrcode.viewfinder", defaultValue: "QRスキャン")),
            IconItem(name: "shield.lefthalf.filled", label: String(localized: "symbolPicker.icon.shield.lefthalf.filled", defaultValue: "シールド半分")),
            IconItem(name: "app", label: String(localized: "symbolPicker.icon.app", defaultValue: "アプリ")),
            IconItem(name: "swift", label: String(localized: "symbolPicker.icon.swift", defaultValue: "Swift")),
            IconItem(name: "cable.connector", label: String(localized: "symbolPicker.icon.cable.connector", defaultValue: "ケーブル")),
            IconItem(name: "cable.connector.horizontal", label: String(localized: "symbolPicker.icon.cable.connector.horizontal", defaultValue: "ケーブル(横)")),
            IconItem(name: "battery.100percent", label: String(localized: "symbolPicker.icon.battery.100percent", defaultValue: "バッテリー満充電")),
            IconItem(name: "battery.50percent", label: String(localized: "symbolPicker.icon.battery.50percent", defaultValue: "バッテリー半分")),
            IconItem(name: "powerplug", label: String(localized: "symbolPicker.icon.powerplug", defaultValue: "電源プラグ")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 10. 健康・フィットネス・スポーツ (Health/Fitness/Sports)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.healthFitness", defaultValue: "健康・運動"), icons: [
            // 健康
            IconItem(name: "heart.circle", label: String(localized: "symbolPicker.icon.heart.circle", defaultValue: "ハート丸")),
            IconItem(name: "heart.text.square", label: String(localized: "symbolPicker.icon.heart.text.square", defaultValue: "バイタル")),
            IconItem(name: "cross.case", label: String(localized: "symbolPicker.icon.cross.case", defaultValue: "救急箱")),
            IconItem(name: "pills", label: String(localized: "symbolPicker.icon.pills", defaultValue: "薬")),
            IconItem(name: "bandage", label: String(localized: "symbolPicker.icon.bandage", defaultValue: "絆創膏")),
            IconItem(name: "lungs", label: String(localized: "symbolPicker.icon.lungs", defaultValue: "肺")),
            IconItem(name: "ear", label: String(localized: "symbolPicker.icon.ear", defaultValue: "耳")),
            IconItem(name: "waveform.path.ecg", label: String(localized: "symbolPicker.icon.waveform.path.ecg", defaultValue: "心電図")),
            IconItem(name: "staroflife", label: String(localized: "symbolPicker.icon.staroflife", defaultValue: "救急マーク")),
            IconItem(name: "allergens", label: String(localized: "symbolPicker.icon.allergens", defaultValue: "アレルゲン")),
            // フィットネス
            IconItem(name: "figure.run", label: String(localized: "symbolPicker.icon.figure.run", defaultValue: "ランニング")),
            IconItem(name: "figure.yoga", label: String(localized: "symbolPicker.icon.figure.yoga", defaultValue: "ヨガ")),
            IconItem(name: "figure.climbing", label: String(localized: "symbolPicker.icon.figure.climbing", defaultValue: "クライミング")),
            IconItem(name: "figure.pool.swim", label: String(localized: "symbolPicker.icon.figure.pool.swim", defaultValue: "プール水泳")),
            IconItem(name: "figure.open.water.swim", label: String(localized: "symbolPicker.icon.figure.open.water.swim", defaultValue: "オープンウォーター")),
            IconItem(name: "figure.skiing.downhill", label: String(localized: "symbolPicker.icon.figure.skiing.downhill", defaultValue: "スキー(滑降)")),
            IconItem(name: "figure.skiing.crosscountry", label: String(localized: "symbolPicker.icon.figure.skiing.crosscountry", defaultValue: "クロスカントリー")),
            IconItem(name: "figure.snowboarding", label: String(localized: "symbolPicker.icon.figure.snowboarding", defaultValue: "スノーボード")),
            IconItem(name: "figure.surfing", label: String(localized: "symbolPicker.icon.figure.surfing", defaultValue: "サーフィン")),
            IconItem(name: "figure.sailing", label: String(localized: "symbolPicker.icon.figure.sailing", defaultValue: "セーリング")),
            IconItem(name: "figure.dance", label: String(localized: "symbolPicker.icon.figure.dance", defaultValue: "ダンス")),
            IconItem(name: "figure.cooldown", label: String(localized: "symbolPicker.icon.figure.cooldown", defaultValue: "クールダウン")),
            IconItem(name: "figure.strengthtraining.traditional", label: String(localized: "symbolPicker.icon.figure.strengthtraining.traditional", defaultValue: "筋トレ")),
            IconItem(name: "figure.strengthtraining.functional", label: String(localized: "symbolPicker.icon.figure.strengthtraining.functional", defaultValue: "ファンクショナル")),
            IconItem(name: "figure.flexibility", label: String(localized: "symbolPicker.icon.figure.flexibility", defaultValue: "柔軟")),
            IconItem(name: "figure.pilates", label: String(localized: "symbolPicker.icon.figure.pilates", defaultValue: "ピラティス")),
            IconItem(name: "figure.taichi", label: String(localized: "symbolPicker.icon.figure.taichi", defaultValue: "太極拳")),
            IconItem(name: "figure.martial.arts", label: String(localized: "symbolPicker.icon.figure.martial.arts", defaultValue: "武道")),
            IconItem(name: "figure.indoor.cycle", label: String(localized: "symbolPicker.icon.figure.indoor.cycle", defaultValue: "インドアサイクル")),
            IconItem(name: "figure.outdoor.cycle", label: String(localized: "symbolPicker.icon.figure.outdoor.cycle", defaultValue: "サイクリング")),
            IconItem(name: "figure.elliptical", label: String(localized: "symbolPicker.icon.figure.elliptical", defaultValue: "エリプティカル")),
            IconItem(name: "figure.stair.stepper", label: String(localized: "symbolPicker.icon.figure.stair.stepper", defaultValue: "ステッパー")),
            IconItem(name: "figure.step.training", label: String(localized: "symbolPicker.icon.figure.step.training", defaultValue: "ステップ")),
            IconItem(name: "figure.cross.training", label: String(localized: "symbolPicker.icon.figure.cross.training", defaultValue: "クロストレーニング")),
            IconItem(name: "figure.mixed.cardio", label: String(localized: "symbolPicker.icon.figure.mixed.cardio", defaultValue: "有酸素ミックス")),
            IconItem(name: "figure.highintensity.intervaltraining", label: String(localized: "symbolPicker.icon.figure.highintensity.intervaltraining", defaultValue: "HIIT")),
            IconItem(name: "figure.core.training", label: String(localized: "symbolPicker.icon.figure.core.training", defaultValue: "体幹トレ")),
            IconItem(name: "figure.jumprope", label: String(localized: "symbolPicker.icon.figure.jumprope", defaultValue: "縄跳び")),
            IconItem(name: "figure.rower", label: String(localized: "symbolPicker.icon.figure.rower", defaultValue: "ローイング")),
            IconItem(name: "figure.roll", label: String(localized: "symbolPicker.icon.figure.roll", defaultValue: "車椅子")),
            IconItem(name: "figure.hand.cycling", label: String(localized: "symbolPicker.icon.figure.hand.cycling", defaultValue: "ハンドサイクル")),
            IconItem(name: "dumbbell", label: String(localized: "symbolPicker.icon.dumbbell", defaultValue: "ダンベル")),
            // スポーツ
            IconItem(name: "figure.basketball", label: String(localized: "symbolPicker.icon.figure.basketball", defaultValue: "バスケ(人)")),
            IconItem(name: "figure.soccer", label: String(localized: "symbolPicker.icon.figure.soccer", defaultValue: "サッカー(人)")),
            IconItem(name: "figure.tennis", label: String(localized: "symbolPicker.icon.figure.tennis", defaultValue: "テニス(人)")),
            IconItem(name: "figure.golf", label: String(localized: "symbolPicker.icon.figure.golf", defaultValue: "ゴルフ(人)")),
            IconItem(name: "figure.boxing", label: String(localized: "symbolPicker.icon.figure.boxing", defaultValue: "ボクシング(人)")),
            IconItem(name: "figure.kickboxing", label: String(localized: "symbolPicker.icon.figure.kickboxing", defaultValue: "キックボクシング")),
            IconItem(name: "figure.wrestling", label: String(localized: "symbolPicker.icon.figure.wrestling", defaultValue: "レスリング")),
            IconItem(name: "figure.fencing", label: String(localized: "symbolPicker.icon.figure.fencing", defaultValue: "フェンシング")),
            IconItem(name: "figure.archery", label: String(localized: "symbolPicker.icon.figure.archery", defaultValue: "アーチェリー")),
            IconItem(name: "figure.baseball", label: String(localized: "symbolPicker.icon.figure.baseball", defaultValue: "野球(人)")),
            IconItem(name: "figure.volleyball", label: String(localized: "symbolPicker.icon.figure.volleyball", defaultValue: "バレー(人)")),
            IconItem(name: "figure.rugby", label: String(localized: "symbolPicker.icon.figure.rugby", defaultValue: "ラグビー(人)")),
            IconItem(name: "figure.hockey", label: String(localized: "symbolPicker.icon.figure.hockey", defaultValue: "ホッケー(人)")),
            IconItem(name: "figure.badminton", label: String(localized: "symbolPicker.icon.figure.badminton", defaultValue: "バドミントン")),
            IconItem(name: "figure.table.tennis", label: String(localized: "symbolPicker.icon.figure.table.tennis", defaultValue: "卓球")),
            IconItem(name: "figure.lacrosse", label: String(localized: "symbolPicker.icon.figure.lacrosse", defaultValue: "ラクロス")),
            IconItem(name: "figure.handball", label: String(localized: "symbolPicker.icon.figure.handball", defaultValue: "ハンドボール")),
            IconItem(name: "figure.cricket", label: String(localized: "symbolPicker.icon.figure.cricket", defaultValue: "クリケット")),
            IconItem(name: "figure.bowling", label: String(localized: "symbolPicker.icon.figure.bowling", defaultValue: "ボウリング")),
            IconItem(name: "figure.curling", label: String(localized: "symbolPicker.icon.figure.curling", defaultValue: "カーリング")),
            IconItem(name: "figure.disc.sports", label: String(localized: "symbolPicker.icon.figure.disc.sports", defaultValue: "ディスクスポーツ")),
            IconItem(name: "figure.equestrian.sports", label: String(localized: "symbolPicker.icon.figure.equestrian.sports", defaultValue: "乗馬")),
            IconItem(name: "figure.fishing", label: String(localized: "symbolPicker.icon.figure.fishing", defaultValue: "釣り")),
            IconItem(name: "figure.hunting", label: String(localized: "symbolPicker.icon.figure.hunting", defaultValue: "狩猟")),
            IconItem(name: "figure.gymnastics", label: String(localized: "symbolPicker.icon.figure.gymnastics", defaultValue: "体操")),
            IconItem(name: "figure.track.and.field", label: String(localized: "symbolPicker.icon.figure.track.and.field", defaultValue: "陸上")),
            IconItem(name: "figure.waterpolo", label: String(localized: "symbolPicker.icon.figure.waterpolo", defaultValue: "水球")),
            IconItem(name: "figure.play", label: String(localized: "symbolPicker.icon.figure.play", defaultValue: "遊び")),
            IconItem(name: "soccerball", label: String(localized: "symbolPicker.icon.soccerball", defaultValue: "サッカーボール")),
            IconItem(name: "basketball", label: String(localized: "symbolPicker.icon.basketball", defaultValue: "バスケットボール")),
            IconItem(name: "tennisball", label: String(localized: "symbolPicker.icon.tennisball", defaultValue: "テニスボール")),
            IconItem(name: "baseball", label: String(localized: "symbolPicker.icon.baseball", defaultValue: "野球ボール")),
            IconItem(name: "football", label: String(localized: "symbolPicker.icon.football", defaultValue: "フットボール")),
            IconItem(name: "american.football", label: String(localized: "symbolPicker.icon.american.football", defaultValue: "アメフトボール")),
            IconItem(name: "volleyball", label: String(localized: "symbolPicker.icon.volleyball", defaultValue: "バレーボール")),
            IconItem(name: "medal.star", label: String(localized: "symbolPicker.icon.medal.star", defaultValue: "スターメダル")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 11. コミュニケーション・SNS (Communication/Social)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.communication", defaultValue: "コミュニケーション"), icons: [
            IconItem(name: "person.badge.plus", label: String(localized: "symbolPicker.icon.person.badge.plus", defaultValue: "人追加")),
            IconItem(name: "person.badge.minus", label: String(localized: "symbolPicker.icon.person.badge.minus", defaultValue: "人削除")),
            IconItem(name: "person.badge.checkmark", label: String(localized: "symbolPicker.icon.person.badge.checkmark", defaultValue: "人認証")),
            IconItem(name: "person.badge.key", label: String(localized: "symbolPicker.icon.person.badge.key", defaultValue: "人と鍵")),
            IconItem(name: "person.badge.clock", label: String(localized: "symbolPicker.icon.person.badge.clock", defaultValue: "人と時計")),
            IconItem(name: "person.badge.shield.checkmark", label: String(localized: "symbolPicker.icon.person.badge.shield.checkmark", defaultValue: "人とシールド")),
            IconItem(name: "envelope.open", label: String(localized: "symbolPicker.icon.envelope.open", defaultValue: "開封")),
            IconItem(name: "envelope.badge", label: String(localized: "symbolPicker.icon.envelope.badge", defaultValue: "封筒バッジ")),
            IconItem(name: "message", label: String(localized: "symbolPicker.icon.message", defaultValue: "メッセージ")),
            IconItem(name: "message.fill", label: String(localized: "symbolPicker.icon.message.fill", defaultValue: "メッセージ(塗り)")),
            IconItem(name: "message.badge", label: String(localized: "symbolPicker.icon.message.badge", defaultValue: "メッセージバッジ")),
            IconItem(name: "bubble.left", label: String(localized: "symbolPicker.icon.bubble.left", defaultValue: "吹き出し左")),
            IconItem(name: "bubble.left.fill", label: String(localized: "symbolPicker.icon.bubble.left.fill", defaultValue: "吹き出し左(塗り)")),
            IconItem(name: "bubble.right", label: String(localized: "symbolPicker.icon.bubble.right", defaultValue: "吹き出し右")),
            IconItem(name: "bubble.left.and.bubble.right", label: String(localized: "symbolPicker.icon.bubble.left.and.bubble.right", defaultValue: "対話")),
            IconItem(name: "bubble", label: String(localized: "symbolPicker.icon.bubble", defaultValue: "吹き出し")),
            IconItem(name: "bubble.and.pencil", label: String(localized: "symbolPicker.icon.bubble.and.pencil", defaultValue: "吹き出しと鉛筆")),
            IconItem(name: "phone.arrow.up.right", label: String(localized: "symbolPicker.icon.phone.arrow.up.right", defaultValue: "発信")),
            IconItem(name: "phone.arrow.down.left", label: String(localized: "symbolPicker.icon.phone.arrow.down.left", defaultValue: "着信")),
            IconItem(name: "hand.wave", label: String(localized: "symbolPicker.icon.hand.wave", defaultValue: "手を振る")),
            IconItem(name: "hand.raised", label: String(localized: "symbolPicker.icon.hand.raised", defaultValue: "挙手")),
            IconItem(name: "hand.raised.fingers.spread", label: String(localized: "symbolPicker.icon.hand.raised.fingers.spread", defaultValue: "パー")),
            IconItem(name: "hand.draw", label: String(localized: "symbolPicker.icon.hand.draw", defaultValue: "手描き")),
            IconItem(name: "hand.point.up", label: String(localized: "symbolPicker.icon.hand.point.up", defaultValue: "指差し上")),
            IconItem(name: "hand.point.right", label: String(localized: "symbolPicker.icon.hand.point.right", defaultValue: "指差し右")),
            IconItem(name: "shared.with.you", label: String(localized: "symbolPicker.icon.shared.with.you", defaultValue: "共有済み")),
            IconItem(name: "at", label: String(localized: "symbolPicker.icon.at", defaultValue: "アットマーク")),
            IconItem(name: "number", label: String(localized: "symbolPicker.icon.number", defaultValue: "ナンバー")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 12. 自然・動物・天気 (Nature/Animals/Weather)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.natureAnimals", defaultValue: "自然・動物"), icons: [
            // 植物
            IconItem(name: "leaf.arrow.triangle.circlepath", label: String(localized: "symbolPicker.icon.leaf.arrow.triangle.circlepath", defaultValue: "エコ・循環")),
            IconItem(name: "tree", label: String(localized: "symbolPicker.icon.tree", defaultValue: "木")),
            IconItem(name: "tree.fill", label: String(localized: "symbolPicker.icon.tree.fill", defaultValue: "木(塗り)")),
            IconItem(name: "drop", label: String(localized: "symbolPicker.icon.drop", defaultValue: "水滴")),
            IconItem(name: "drop.fill", label: String(localized: "symbolPicker.icon.drop.fill", defaultValue: "水滴(塗り)")),
            IconItem(name: "drop.degreesign", label: String(localized: "symbolPicker.icon.drop.degreesign", defaultValue: "湿度")),
            // 天気
            IconItem(name: "sun.max", label: String(localized: "symbolPicker.icon.sun.max", defaultValue: "太陽")),
            IconItem(name: "sun.max.fill", label: String(localized: "symbolPicker.icon.sun.max.fill", defaultValue: "太陽(塗り)")),
            IconItem(name: "sun.min", label: String(localized: "symbolPicker.icon.sun.min", defaultValue: "太陽(小)")),
            IconItem(name: "sun.and.horizon", label: String(localized: "symbolPicker.icon.sun.and.horizon", defaultValue: "日の出・日の入り")),
            IconItem(name: "sun.dust", label: String(localized: "symbolPicker.icon.sun.dust", defaultValue: "霞む太陽")),
            IconItem(name: "sun.haze", label: String(localized: "symbolPicker.icon.sun.haze", defaultValue: "もやの太陽")),
            IconItem(name: "sunrise", label: String(localized: "symbolPicker.icon.sunrise", defaultValue: "日の出")),
            IconItem(name: "sunrise.fill", label: String(localized: "symbolPicker.icon.sunrise.fill", defaultValue: "日の出(塗り)")),
            IconItem(name: "sunset", label: String(localized: "symbolPicker.icon.sunset", defaultValue: "日の入り")),
            IconItem(name: "sunset.fill", label: String(localized: "symbolPicker.icon.sunset.fill", defaultValue: "日の入り(塗り)")),
            IconItem(name: "moon", label: String(localized: "symbolPicker.icon.moon", defaultValue: "月")),
            IconItem(name: "moon.fill", label: String(localized: "symbolPicker.icon.moon.fill", defaultValue: "月(塗り)")),
            IconItem(name: "moon.stars", label: String(localized: "symbolPicker.icon.moon.stars", defaultValue: "月と星")),
            IconItem(name: "moon.stars.fill", label: String(localized: "symbolPicker.icon.moon.stars.fill", defaultValue: "月と星(塗り)")),
            IconItem(name: "sparkle", label: String(localized: "symbolPicker.icon.sparkle", defaultValue: "きらめき")),
            IconItem(name: "rainbow", label: String(localized: "symbolPicker.icon.rainbow", defaultValue: "虹")),
            IconItem(name: "cloud", label: String(localized: "symbolPicker.icon.cloud", defaultValue: "雲")),
            IconItem(name: "cloud.fill", label: String(localized: "symbolPicker.icon.cloud.fill", defaultValue: "雲(塗り)")),
            IconItem(name: "cloud.rain", label: String(localized: "symbolPicker.icon.cloud.rain", defaultValue: "雨")),
            IconItem(name: "cloud.rain.fill", label: String(localized: "symbolPicker.icon.cloud.rain.fill", defaultValue: "雨(塗り)")),
            IconItem(name: "cloud.bolt", label: String(localized: "symbolPicker.icon.cloud.bolt", defaultValue: "雷")),
            IconItem(name: "cloud.bolt.fill", label: String(localized: "symbolPicker.icon.cloud.bolt.fill", defaultValue: "雷(塗り)")),
            IconItem(name: "cloud.bolt.rain", label: String(localized: "symbolPicker.icon.cloud.bolt.rain", defaultValue: "雷雨")),
            IconItem(name: "cloud.snow", label: String(localized: "symbolPicker.icon.cloud.snow", defaultValue: "雪")),
            IconItem(name: "cloud.snow.fill", label: String(localized: "symbolPicker.icon.cloud.snow.fill", defaultValue: "雪(塗り)")),
            IconItem(name: "cloud.sun", label: String(localized: "symbolPicker.icon.cloud.sun", defaultValue: "晴れ時々曇り")),
            IconItem(name: "cloud.sun.fill", label: String(localized: "symbolPicker.icon.cloud.sun.fill", defaultValue: "晴れ時々曇り(塗り)")),
            IconItem(name: "cloud.sun.rain", label: String(localized: "symbolPicker.icon.cloud.sun.rain", defaultValue: "にわか雨")),
            IconItem(name: "cloud.drizzle", label: String(localized: "symbolPicker.icon.cloud.drizzle", defaultValue: "霧雨")),
            IconItem(name: "cloud.fog", label: String(localized: "symbolPicker.icon.cloud.fog", defaultValue: "霧")),
            IconItem(name: "wind", label: String(localized: "symbolPicker.icon.wind", defaultValue: "風")),
            IconItem(name: "wind.snow", label: String(localized: "symbolPicker.icon.wind.snow", defaultValue: "吹雪")),
            IconItem(name: "snowflake", label: String(localized: "symbolPicker.icon.snowflake", defaultValue: "雪の結晶")),
            IconItem(name: "umbrella", label: String(localized: "symbolPicker.icon.umbrella", defaultValue: "傘")),
            IconItem(name: "umbrella.fill", label: String(localized: "symbolPicker.icon.umbrella.fill", defaultValue: "傘(塗り)")),
            IconItem(name: "water.waves", label: String(localized: "symbolPicker.icon.water.waves", defaultValue: "波")),
            IconItem(name: "thermometer", label: String(localized: "symbolPicker.icon.thermometer", defaultValue: "温度計")),
            IconItem(name: "thermometer.high", label: String(localized: "symbolPicker.icon.thermometer.high", defaultValue: "高温")),
            IconItem(name: "thermometer.low", label: String(localized: "symbolPicker.icon.thermometer.low", defaultValue: "低温")),
            // 動物
            IconItem(name: "pawprint", label: String(localized: "symbolPicker.icon.pawprint", defaultValue: "足跡")),
            IconItem(name: "pawprint.fill", label: String(localized: "symbolPicker.icon.pawprint.fill", defaultValue: "足跡(塗り)")),
            IconItem(name: "cat", label: String(localized: "symbolPicker.icon.cat", defaultValue: "猫")),
            IconItem(name: "cat.fill", label: String(localized: "symbolPicker.icon.cat.fill", defaultValue: "猫(塗り)")),
            IconItem(name: "dog", label: String(localized: "symbolPicker.icon.dog", defaultValue: "犬")),
            IconItem(name: "dog.fill", label: String(localized: "symbolPicker.icon.dog.fill", defaultValue: "犬(塗り)")),
            IconItem(name: "bird", label: String(localized: "symbolPicker.icon.bird", defaultValue: "鳥")),
            IconItem(name: "bird.fill", label: String(localized: "symbolPicker.icon.bird.fill", defaultValue: "鳥(塗り)")),
            IconItem(name: "fish", label: String(localized: "symbolPicker.icon.fish", defaultValue: "魚")),
            IconItem(name: "fish.fill", label: String(localized: "symbolPicker.icon.fish.fill", defaultValue: "魚(塗り)")),
            IconItem(name: "tortoise", label: String(localized: "symbolPicker.icon.tortoise", defaultValue: "亀")),
            IconItem(name: "tortoise.fill", label: String(localized: "symbolPicker.icon.tortoise.fill", defaultValue: "亀(塗り)")),
            IconItem(name: "hare", label: String(localized: "symbolPicker.icon.hare", defaultValue: "うさぎ")),
            IconItem(name: "hare.fill", label: String(localized: "symbolPicker.icon.hare.fill", defaultValue: "うさぎ(塗り)")),
            IconItem(name: "ant", label: String(localized: "symbolPicker.icon.ant", defaultValue: "蟻")),
            IconItem(name: "ant.fill", label: String(localized: "symbolPicker.icon.ant.fill", defaultValue: "蟻(塗り)")),
            IconItem(name: "ladybug", label: String(localized: "symbolPicker.icon.ladybug", defaultValue: "てんとう虫")),
            IconItem(name: "ladybug.fill", label: String(localized: "symbolPicker.icon.ladybug.fill", defaultValue: "てんとう虫(塗り)")),
            IconItem(name: "lizard", label: String(localized: "symbolPicker.icon.lizard", defaultValue: "トカゲ")),
            IconItem(name: "lizard.fill", label: String(localized: "symbolPicker.icon.lizard.fill", defaultValue: "トカゲ(塗り)")),
            IconItem(name: "teddybear", label: String(localized: "symbolPicker.icon.teddybear", defaultValue: "テディベア")),
            IconItem(name: "fossil.shell", label: String(localized: "symbolPicker.icon.fossil.shell", defaultValue: "化石")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 13. 家・生活・家電 (Home/Living/Appliances)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.homeLiving", defaultValue: "家・生活"), icons: [
            IconItem(name: "house.circle", label: String(localized: "symbolPicker.icon.house.circle", defaultValue: "家丸")),
            IconItem(name: "house.and.flag", label: String(localized: "symbolPicker.icon.house.and.flag", defaultValue: "家と旗")),
            IconItem(name: "sofa", label: String(localized: "symbolPicker.icon.sofa", defaultValue: "ソファ")),
            IconItem(name: "sofa.fill", label: String(localized: "symbolPicker.icon.sofa.fill", defaultValue: "ソファ(塗り)")),
            IconItem(name: "bathtub", label: String(localized: "symbolPicker.icon.bathtub", defaultValue: "浴槽")),
            IconItem(name: "bathtub.fill", label: String(localized: "symbolPicker.icon.bathtub.fill", defaultValue: "浴槽(塗り)")),
            IconItem(name: "shower", label: String(localized: "symbolPicker.icon.shower", defaultValue: "シャワー")),
            IconItem(name: "shower.handheld", label: String(localized: "symbolPicker.icon.shower.handheld", defaultValue: "シャワーヘッド")),
            IconItem(name: "toilet", label: String(localized: "symbolPicker.icon.toilet", defaultValue: "トイレ")),
            IconItem(name: "sink", label: String(localized: "symbolPicker.icon.sink", defaultValue: "シンク")),
            IconItem(name: "spigot", label: String(localized: "symbolPicker.icon.spigot", defaultValue: "蛇口")),
            IconItem(name: "washer", label: String(localized: "symbolPicker.icon.washer", defaultValue: "洗濯機")),
            IconItem(name: "dryer", label: String(localized: "symbolPicker.icon.dryer", defaultValue: "乾燥機")),
            IconItem(name: "dishwasher", label: String(localized: "symbolPicker.icon.dishwasher", defaultValue: "食洗機")),
            IconItem(name: "refrigerator", label: String(localized: "symbolPicker.icon.refrigerator", defaultValue: "冷蔵庫")),
            IconItem(name: "microwave", label: String(localized: "symbolPicker.icon.microwave", defaultValue: "電子レンジ")),
            IconItem(name: "lightbulb.led", label: String(localized: "symbolPicker.icon.lightbulb.led", defaultValue: "LED電球")),
            IconItem(name: "lamp.desk", label: String(localized: "symbolPicker.icon.lamp.desk", defaultValue: "デスクランプ")),
            IconItem(name: "lamp.floor", label: String(localized: "symbolPicker.icon.lamp.floor", defaultValue: "フロアランプ")),
            IconItem(name: "lamp.table", label: String(localized: "symbolPicker.icon.lamp.table", defaultValue: "テーブルランプ")),
            IconItem(name: "lamp.ceiling", label: String(localized: "symbolPicker.icon.lamp.ceiling", defaultValue: "シーリングライト")),
            IconItem(name: "lightswitch.on", label: String(localized: "symbolPicker.icon.lightswitch.on", defaultValue: "スイッチON")),
            IconItem(name: "fan", label: String(localized: "symbolPicker.icon.fan", defaultValue: "扇風機")),
            IconItem(name: "fan.fill", label: String(localized: "symbolPicker.icon.fan.fill", defaultValue: "扇風機(塗り)")),
            IconItem(name: "air.conditioner.horizontal", label: String(localized: "symbolPicker.icon.air.conditioner.horizontal", defaultValue: "エアコン")),
            IconItem(name: "dehumidifier", label: String(localized: "symbolPicker.icon.dehumidifier", defaultValue: "除湿機")),
            IconItem(name: "humidifier", label: String(localized: "symbolPicker.icon.humidifier", defaultValue: "加湿器")),
            IconItem(name: "chair", label: String(localized: "symbolPicker.icon.chair", defaultValue: "椅子")),
            IconItem(name: "chair.lounge", label: String(localized: "symbolPicker.icon.chair.lounge", defaultValue: "ラウンジチェア")),
            IconItem(name: "table.furniture", label: String(localized: "symbolPicker.icon.table.furniture", defaultValue: "テーブル")),
            IconItem(name: "cabinet", label: String(localized: "symbolPicker.icon.cabinet", defaultValue: "キャビネット")),
            IconItem(name: "fireplace", label: String(localized: "symbolPicker.icon.fireplace", defaultValue: "暖炉")),
            IconItem(name: "door.left.hand.open", label: String(localized: "symbolPicker.icon.door.left.hand.open", defaultValue: "ドア(開)")),
            IconItem(name: "door.left.hand.closed", label: String(localized: "symbolPicker.icon.door.left.hand.closed", defaultValue: "ドア(閉)")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 14. 記号・矢印・UI (Symbols/Arrows/UI)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.symbolsArrows", defaultValue: "記号・矢印"), icons: [
            IconItem(name: "exclamationmark.triangle", label: String(localized: "symbolPicker.icon.exclamationmark.triangle", defaultValue: "警告")),
            IconItem(name: "exclamationmark.triangle.fill", label: String(localized: "symbolPicker.icon.exclamationmark.triangle.fill", defaultValue: "警告(塗り)")),
            IconItem(name: "info.circle", label: String(localized: "symbolPicker.icon.info.circle", defaultValue: "情報")),
            IconItem(name: "info.circle.fill", label: String(localized: "symbolPicker.icon.info.circle.fill", defaultValue: "情報(塗り)")),
            IconItem(name: "questionmark.circle", label: String(localized: "symbolPicker.icon.questionmark.circle", defaultValue: "ヘルプ")),
            IconItem(name: "questionmark.circle.fill", label: String(localized: "symbolPicker.icon.questionmark.circle.fill", defaultValue: "ヘルプ(塗り)")),
            IconItem(name: "xmark.circle", label: String(localized: "symbolPicker.icon.xmark.circle", defaultValue: "バツ丸")),
            IconItem(name: "xmark.circle.fill", label: String(localized: "symbolPicker.icon.xmark.circle.fill", defaultValue: "バツ丸(塗り)")),
            IconItem(name: "plus.circle", label: String(localized: "symbolPicker.icon.plus.circle", defaultValue: "プラス丸")),
            IconItem(name: "plus.circle.fill", label: String(localized: "symbolPicker.icon.plus.circle.fill", defaultValue: "プラス丸(塗り)")),
            IconItem(name: "minus.circle", label: String(localized: "symbolPicker.icon.minus.circle", defaultValue: "マイナス丸")),
            IconItem(name: "minus.circle.fill", label: String(localized: "symbolPicker.icon.minus.circle.fill", defaultValue: "マイナス丸(塗り)")),
            IconItem(name: "infinity", label: String(localized: "symbolPicker.icon.infinity", defaultValue: "無限")),
            IconItem(name: "repeat", label: String(localized: "symbolPicker.icon.repeat", defaultValue: "リピート")),
            IconItem(name: "repeat.1", label: String(localized: "symbolPicker.icon.repeat.1", defaultValue: "1曲リピート")),
            IconItem(name: "shuffle", label: String(localized: "symbolPicker.icon.shuffle", defaultValue: "シャッフル")),
            IconItem(name: "arrow.up", label: String(localized: "symbolPicker.icon.arrow.up", defaultValue: "上矢印")),
            IconItem(name: "arrow.down", label: String(localized: "symbolPicker.icon.arrow.down", defaultValue: "下矢印")),
            IconItem(name: "arrow.left", label: String(localized: "symbolPicker.icon.arrow.left", defaultValue: "左矢印")),
            IconItem(name: "arrow.right", label: String(localized: "symbolPicker.icon.arrow.right", defaultValue: "右矢印")),
            IconItem(name: "arrow.left.arrow.right", label: String(localized: "symbolPicker.icon.arrow.left.arrow.right", defaultValue: "左右矢印")),
            IconItem(name: "arrow.clockwise", label: String(localized: "symbolPicker.icon.arrow.clockwise", defaultValue: "時計回り")),
            IconItem(name: "arrow.counterclockwise", label: String(localized: "symbolPicker.icon.arrow.counterclockwise", defaultValue: "反時計回り")),
            IconItem(name: "arrow.2.circlepath", label: String(localized: "symbolPicker.icon.arrow.2.circlepath", defaultValue: "更新")),
            IconItem(name: "arrow.triangle.branch", label: String(localized: "symbolPicker.icon.arrow.triangle.branch", defaultValue: "分岐")),
            IconItem(name: "compass.drawing", label: String(localized: "symbolPicker.icon.compass.drawing", defaultValue: "コンパス")),
            IconItem(name: "scope", label: String(localized: "symbolPicker.icon.scope", defaultValue: "スコープ")),
            IconItem(name: "viewfinder", label: String(localized: "symbolPicker.icon.viewfinder", defaultValue: "ビューファインダー")),
            IconItem(name: "viewfinder.rectangular", label: String(localized: "symbolPicker.icon.viewfinder.rectangular", defaultValue: "矩形ファインダー")),
            IconItem(name: "aspectratio", label: String(localized: "symbolPicker.icon.aspectratio", defaultValue: "アスペクト比")),
            IconItem(name: "cursorarrow", label: String(localized: "symbolPicker.icon.cursorarrow", defaultValue: "カーソル")),
            IconItem(name: "cursorarrow.click", label: String(localized: "symbolPicker.icon.cursorarrow.click", defaultValue: "クリック")),
            IconItem(name: "sidebar.left", label: String(localized: "symbolPicker.icon.sidebar.left", defaultValue: "サイドバー左")),
            IconItem(name: "sidebar.right", label: String(localized: "symbolPicker.icon.sidebar.right", defaultValue: "サイドバー右")),
        ]),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // MARK: 15. その他・ユニーク (Other/Unique)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        IconCategory(title: String(localized: "symbolPicker.category.other", defaultValue: "その他"), icons: [
            IconItem(name: "waveform", label: String(localized: "symbolPicker.icon.waveform", defaultValue: "波形")),
            IconItem(name: "waveform.path", label: String(localized: "symbolPicker.icon.waveform.path", defaultValue: "波形パス")),
            IconItem(name: "cube", label: String(localized: "symbolPicker.icon.cube", defaultValue: "立方体")),
            IconItem(name: "cylinder", label: String(localized: "symbolPicker.icon.cylinder", defaultValue: "円柱")),
            IconItem(name: "cone", label: String(localized: "symbolPicker.icon.cone", defaultValue: "円錐")),
            IconItem(name: "pyramid", label: String(localized: "symbolPicker.icon.pyramid", defaultValue: "ピラミッド")),
            IconItem(name: "timer", label: String(localized: "symbolPicker.icon.timer", defaultValue: "タイマー")),
            IconItem(name: "stopwatch", label: String(localized: "symbolPicker.icon.stopwatch", defaultValue: "ストップウォッチ")),
            IconItem(name: "alarm", label: String(localized: "symbolPicker.icon.alarm", defaultValue: "アラーム")),
            IconItem(name: "gauge", label: String(localized: "symbolPicker.icon.gauge", defaultValue: "ゲージ")),
            IconItem(name: "gauge.high", label: String(localized: "symbolPicker.icon.gauge.high", defaultValue: "ゲージ高")),
            IconItem(name: "gauge.low", label: String(localized: "symbolPicker.icon.gauge.low", defaultValue: "ゲージ低")),
            IconItem(name: "speedometer", label: String(localized: "symbolPicker.icon.speedometer", defaultValue: "速度計")),
            IconItem(name: "nosign", label: String(localized: "symbolPicker.icon.nosign", defaultValue: "禁止")),
            IconItem(name: "flag.checkered", label: String(localized: "symbolPicker.icon.flag.checkered", defaultValue: "チェッカーフラッグ")),
            IconItem(name: "checkmark.seal", label: String(localized: "symbolPicker.icon.checkmark.seal", defaultValue: "認証シール")),
            IconItem(name: "checkmark.seal.fill", label: String(localized: "symbolPicker.icon.checkmark.seal.fill", defaultValue: "認証シール(塗り)")),
            IconItem(name: "scroll", label: String(localized: "symbolPicker.icon.scroll", defaultValue: "巻物")),
            IconItem(name: "scroll.fill", label: String(localized: "symbolPicker.icon.scroll.fill", defaultValue: "巻物(塗り)")),
            IconItem(name: "magazine", label: String(localized: "symbolPicker.icon.magazine", defaultValue: "雑誌")),
            IconItem(name: "magazine.fill", label: String(localized: "symbolPicker.icon.magazine.fill", defaultValue: "雑誌(塗り)")),
            IconItem(name: "checklist", label: String(localized: "symbolPicker.icon.checklist", defaultValue: "チェックリスト")),
            IconItem(name: "square.stack", label: String(localized: "symbolPicker.icon.square.stack", defaultValue: "スタック")),
            IconItem(name: "tuningfork", label: String(localized: "symbolPicker.icon.tuningfork", defaultValue: "音叉")),
            IconItem(name: "checkerboard.rectangle", label: String(localized: "symbolPicker.icon.checkerboard.rectangle", defaultValue: "チェッカーボード")),
        ]),
    ]
    // swiftlint:enable function_body_length
}
